In [ ]:
import pandas as pd

expression_final = pd.read_csv('/content/FINAL_NSCLC_EXPRESSION.csv')
expression_scaled = pd.read_csv('/content/NSCLC_expression_scaled.csv')

print("FINAL_NSCLC_EXPRESSION")
print(expression_final.shape)

print("\nNSCLC_expression_scaled")
print(expression_scaled.shape)

print("\nFINAL_NSCLC_EXPRESSION HEAD")
display(expression_final.head())

print("\nNSCLC_expression_scaled HEAD")
display(expression_scaled.head())

FINAL_NSCLC_EXPRESSION
(140, 19206)

NSCLC_expression_scaled
(140, 8147)

FINAL_NSCLC_EXPRESSION HEAD

,Unnamed: 0,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),FIRRM (55732),FGR (2268),CFH (3075),FUCA2 (2519),GCLC (2729),...,H3C3 (8352),CIMIP3 (114841037),SMIM42 (117981789),NPBWR1 (2831),ACTL10 (170487),PANO1 (101927423),HRURF (120766137),PRRC2B (84726),F8A2 (474383),F8A1 (8263)
0,ACH-001113,4.956577,0.0,7.577648,3.179411,4.765742,0.037483,1.510547,3.103039,6.697482,...,0.093516,0.0,0.0,0.414727,0.077634,0.411901,0.0,5.134808,1.214541,4.315653
1,ACH-000327,3.759710,0.0,6.062055,1.931978,2.801039,0.008343,3.155547,6.022998,3.989239,...,0.764529,0.0,0.0,0.167291,0.984557,0.491320,0.0,3.744742,3.018606,0.254729
2,ACH-000705,4.643816,0.0,6.477998,2.449667,4.400859,0.038055,0.225467,2.721062,6.441122,...,0.075771,0.0,0.0,0.042438,0.259432,0.600953,0.0,5.131668,0.258232,4.698113
3,ACH-000769,5.079698,0.0,6.241085,2.674804,4.322995,0.000000,0.147421,5.922712,5.998331,...,0.000000,0.0,0.0,0.724773,0.610963,0.372742,0.0,6.628902,1.108538,4.414291
4,ACH-000528,4.764797,0.0,7.203309,3.102794,4.878814,0.015458,1.114007,6.858242,4.421156,...,0.405741,0.0,0.0,0.033873,0.096988,0.530759,0.0,6.522283,0.000000,5.673958

NSCLC_expression_scaled HEAD

,ModelID,TSPAN6 (7105),CFH (3075),FUCA2 (2519),GCLC (2729),NIPAL3 (57185),LAS1L (81887),ENPP4 (22875),SEMA3F (6405),CFTR (1080),...,ARHGAP11B (89839),NOTCH2NLB (100996763),ASDURF (110599588),NOTCH2NLR (101929796),DERPC (113455421),NOTCH2NLC (100996717),H3C2 (8358),NPBWR1 (2831),F8A2 (474383),F8A1 (8263)
0,ACH-001113,0.606535,-0.560840,-2.644608,0.501161,0.580265,-0.283453,0.084252,0.483254,-0.390686,...,-1.211794,-0.706244,3.465299,1.112084,1.724145,0.353247,2.170848,-0.185473,0.183697,-0.474737
1,ACH-000327,-0.504443,0.161351,0.098725,-1.374420,-0.188582,-1.931341,0.761490,-1.280325,0.596369,...,-1.315398,-1.346125,-1.254118,-1.520229,-2.586064,1.754330,-0.169212,-0.444057,1.581376,-4.115950
2,ACH-000705,0.316218,-1.125019,-3.003480,0.323620,-0.233423,-0.333249,0.409922,0.548669,-0.373631,...,-0.268577,-1.080501,-0.836820,0.735921,0.250250,-0.753904,0.406407,-0.574535,-0.557194,-0.131806
3,ACH-000769,0.720820,-1.159283,0.004505,0.016968,-0.310588,-0.232841,0.173370,-0.548671,0.286691,...,0.274256,2.037860,-0.563779,3.022382,0.277748,1.366609,-0.398641,0.138544,0.101572,-0.386293
4,ACH-000528,0.428517,-0.734930,0.883446,-1.075298,0.502380,-0.152433,1.574718,0.869558,-0.318270,...,0.043276,-0.852255,0.339073,0.925263,-1.126724,-0.356900,-0.007251,-0.583486,-0.757256,0.743182

In [ ]:
gdsc_df = pd.read_csv('/content/FINAL_NSCLC_GDSC.csv')
smiles_df = pd.read_csv('/content/GDSC_FULL_SMILES.csv')
mutation_df = pd.read_csv('/content/CCLE_mutations.csv')

print("GDSC Shape:", gdsc_df.shape)
print("SMILES Shape:", smiles_df.shape)
print("Mutation Shape:", mutation_df.shape)

/tmp/ipykernel_3496/2166916924.py:3: DtypeWarning: Columns (3,19,20,22,28,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  mutation_df = pd.read_csv('/content/CCLE_mutations.csv')

GDSC Shape: (26346, 16)
SMILES Shape: (229, 2)
Mutation Shape: (588092, 32)

In [ ]:
cancer_emb = pd.read_csv('/content/CANCER_EMBEDDINGS.csv')

print(cancer_emb.shape)
display(cancer_emb.head())

(92, 258)

,ModelID,0,1,2,3,4,5,6,7,8,...,247,248,249,250,251,252,253,254,255,SangerModelID
0,ACH-000769,0.000000,0.000000,0.000000,2.933871,0.000000,5.080203,0.000000,1.007952,0.000000,...,4.894772,7.563287,3.385449,1.911925,0.000000,0.000000,0.000000,1.293958,0.000000,SIDM00548
1,ACH-000528,0.000000,0.000000,0.000000,8.689753,0.000000,9.536879,0.000000,3.491262,0.000000,...,0.000000,0.000000,0.919749,5.411538,0.000000,0.000000,0.449896,0.000000,0.000000,SIDM00494
2,ACH-000585,1.601672,0.000000,1.348526,0.000000,0.195043,1.056408,0.000000,0.000000,0.503666,...,0.000000,0.000000,0.000000,3.689462,3.579045,0.260818,0.000000,3.186861,0.938508,SIDM01044
3,ACH-000176,7.361752,0.714724,3.704599,0.000000,3.283474,4.789253,0.000000,2.506674,0.699377,...,0.000000,0.000000,0.000000,1.272413,8.481025,0.000000,0.000000,0.000000,0.759241,SIDM00341
4,ACH-000587,1.381379,0.104786,3.412546,0.000000,1.757902,1.597279,1.692989,2.678646,6.008335,...,0.000000,1.814873,0.260602,0.000000,5.809113,0.124171,0.621711,0.000000,2.952305,SIDM00759

In [ ]:
print(mutation_df.columns.tolist())
mutation_df.head()

['Hugo_Symbol', 'Entrez_Gene_Id', 'NCBI_Build', 'Chromosome', 'Start_position', 'End_position', 'Strand', 'Variant_Classification', 'Variant_Type', 'Reference_Allele', 'Alternate_Allele', 'dbSNP_RS', 'dbSNP_Val_Status', 'Genome_Change', 'Annotation_Transcript', 'DepMap_ID', 'cDNA_Change', 'Codon_Change', 'Protein_Change', 'isDeleterious', 'isTCGAhotspot', 'TCGAhsCnt', 'isCOSMIChotspot', 'COSMIChsCnt', 'ExAC_AF', 'Variant_annotation', 'CGA_WES_AC', 'HC_AC', 'RD_AC', 'RNAseq_AC', 'SangerWES_AC', 'WGS_AC']

,Hugo_Symbol,Entrez_Gene_Id,NCBI_Build,Chromosome,Start_position,End_position,Strand,Variant_Classification,Variant_Type,Reference_Allele,...,isCOSMIChotspot,COSMIChsCnt,ExAC_AF,Variant_annotation,CGA_WES_AC,HC_AC,RD_AC,RNAseq_AC,SangerWES_AC,WGS_AC
0,VPS13D,55187,37,1,12359347,12359347,+,Nonsense_Mutation,SNP,C,...,False,0.0,NaN,damaging,34:213,NaN,NaN,NaN,34:221,NaN
1,AADACL4,343066,37,1,12726308,12726322,+,In_Frame_Del,DEL,CTGGCGTGACGCCAT,...,False,3.0,NaN,other non-conserving,57:141,NaN,NaN,NaN,9:0,28:32
2,IFNLR1,163702,37,1,24484172,24484172,+,Silent,SNP,G,...,False,0.0,NaN,silent,118:0,NaN,NaN,10:0,118:0,18:0
3,TMEM57,55219,37,1,25785018,25785019,+,Frame_Shift_Ins,INS,-,...,False,0.0,NaN,damaging,NaN,NaN,NaN,6:28,NaN,NaN
4,ZSCAN20,7579,37,1,33954141,33954141,+,Missense_Mutation,SNP,T,...,False,0.0,NaN,other non-conserving,28:62,NaN,NaN,NaN,27:61,NaN

In [ ]:
cancer_emb = pd.read_csv('/content/CANCER_EMBEDDINGS.csv')

print(cancer_emb.shape)
print(cancer_emb.columns[:10])

(92, 258)
Index(['ModelID', '0', '1', '2', '3', '4', '5', '6', '7', '8'], dtype='object')

In [ ]:
import pandas as pd

smiles_df = pd.read_csv('/content/GDSC_FULL_SMILES.csv')

print(smiles_df.shape)
print(smiles_df.columns)
display(smiles_df.head())

(229, 2)
Index(['Drug', 'CanonicalSMILES'], dtype='object')

           Drug                                    CanonicalSMILES
0  Camptothecin  CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3...
1   Vinblastine  CCC1(CC2CC(C3=C(CCN(C2)C1)C4=CC=CC=C4N3)(C5=C(...
2     Cisplatin                                       N.N.Cl[Pt]Cl
3    Cytarabine                 C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)O
4     Docetaxel  CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)...

In [ ]:
!pip install rdkit

Collecting rdkit
  Downloading rdkit-2026.3.2-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.2-cp312-cp312-manylinux_2_28_x86_64.whl (37.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.1/37.1 MB 38.4 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.2

In [ ]:
#Requirement: Mutation Data Added

In [ ]:
nsclc_ids = set(cancer_emb["ModelID"])

print("NSCLC Cell Lines:")
print(len(nsclc_ids))

print("\nMutation Cell Lines:")
print(mutation_df["DepMap_ID"].nunique())

overlap = set(mutation_df["DepMap_ID"]).intersection(nsclc_ids)

print("\nOverlap:")
print(len(overlap))

NSCLC Cell Lines:
92

Mutation Cell Lines:
962

Overlap:
90

In [ ]:
mutation_df["Hugo_Symbol"].value_counts().head(30)

Hugo_Symbol
TTN       2237
MUC16     1117
TP53       773
RYR2       548
OBSCN      547
LRP1B      496
CSMD3      484
SYNE1      454
USH2A      451
KMT2D      439
ZFHX4      436
MUC4       435
DST        415
PCLO       414
FLG        386
FAT3       377
MT-ND5     372
CSMD1      360
PLEC       359
RYR1       353
ABCA13     351
HMCN1      350
MACF1      325
MUC5B      310
DNAH5      308
GPR98      307
RYR3       305
FAT4       305
KMT2C      304
NEB        304
Name: count, dtype: int64

In [ ]:
#checking NSCLC Mutation Cells are present?

nsclc_driver_genes = [
    "TP53",
    "EGFR",
    "KRAS",
    "STK11",
    "KEAP1",
    "BRAF",
    "PIK3CA",
    "ALK",
    "ROS1",
    "MET",
    "ERBB2",
    "NF1",
    "RB1",
    "SMARCA4",
    "CDKN2A",
    "PTEN"
]

for gene in nsclc_driver_genes:

    count = mutation_df[
        mutation_df["Hugo_Symbol"] == gene
    ]["DepMap_ID"].nunique()

    print(gene, count)

TP53 657
EGFR 89
KRAS 165
STK11 62
KEAP1 72
BRAF 126
PIK3CA 110
ALK 102
ROS1 105
MET 52
ERBB2 55
NF1 131
RB1 103
SMARCA4 136
CDKN2A 105
PTEN 118

In [ ]:
nsclc_driver_genes = [
    "TP53","EGFR","KRAS","STK11",
    "KEAP1","BRAF","PIK3CA","ALK",
    "ROS1","MET","ERBB2","NF1",
    "RB1","SMARCA4","CDKN2A","PTEN"
]

nsclc_ids = set(cancer_emb["ModelID"])

mutation_subset = mutation_df[
    mutation_df["DepMap_ID"].isin(nsclc_ids)
]

mutation_matrix = pd.DataFrame(
    index=sorted(nsclc_ids)
)

for gene in nsclc_driver_genes:

    mutated_cells = set(
        mutation_subset[
            mutation_subset["Hugo_Symbol"] == gene
        ]["DepMap_ID"]
    )

    mutation_matrix[gene] = (
        mutation_matrix.index.isin(mutated_cells)
    ).astype(int)

mutation_matrix.reset_index(inplace=True)

mutation_matrix.rename(
    columns={"index":"ModelID"},
    inplace=True
)

print(mutation_matrix.shape)

display(mutation_matrix.head())

(92, 17)

,ModelID,TP53,EGFR,KRAS,STK11,KEAP1,BRAF,PIK3CA,ALK,ROS1,MET,ERBB2,NF1,RB1,SMARCA4,CDKN2A,PTEN
0,ACH-000012,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,ACH-000015,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,ACH-000021,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0
3,ACH-000030,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,ACH-000035,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [ ]:
mutation_matrix.to_csv(
    "MUTATION_MATRIX.csv",
    index=False
)

In [ ]:
from tensorflow.keras.models import load_model

model = load_model(
    "/content/Final_NSCLC_Drug_Response_Model.keras",
    compile=False
)

model.summary()

Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ CancerEmbedding     │ (None, 256)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ DrugEmbedding       │ (None, 256)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ reshape_1 (Reshape) │ (None, 1, 256)    │          0 │ DrugEmbedding[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ reshape (Reshape)   │ (None, 1, 256)    │          0 │ CancerEmbedding[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 1, 256)    │    263,168 │ reshape_1[0][0],  │
│ (MultiHeadAttentio… │                   │            │ reshape[0][0],    │
│                     │                   │            │ reshape_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 1, 256)    │    263,168 │ reshape[0][0],    │
│ (MultiHeadAttentio… │                   │            │ reshape_1[0][0],  │
│                     │                   │            │ reshape[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalization │ (None, 1, 256)    │        512 │ multi_head_atten… │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 1, 256)    │        512 │ multi_head_atten… │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 256)       │          0 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_1 (Flatten) │ (None, 256)       │          0 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 1024)      │          0 │ CancerEmbedding[… │
│ (Concatenate)       │                   │            │ DrugEmbedding[0]… │
│                     │                   │            │ flatten[0][0],    │
│                     │                   │            │ flatten_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_28 (Dense)    │ (None, 512)       │    524,800 │ concatenate[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_14          │ (None, 512)       │          0 │ dense_28[0][0]    │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_29 (Dense)    │ (None, 256)       │    131,328 │ dropout_14[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_15          │ (None, 256)       │          0 │ dense_29[0][0]    │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_30 (Dense)    │ (None, 128)       │     32,896 │ dropout_15[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ LN_IC50 (Dense)     │ (None, 1)         │        129 │ dense_30[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 1,216,513 (4.64 MB)

 Trainable params: 1,216,513 (4.64 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
cancer_emb = pd.read_csv('/content/CANCER_EMBEDDINGS.csv')
mutation_matrix = pd.read_csv('/content/MUTATION_MATRIX.csv')

combined_cell_features = cancer_emb.merge(
    mutation_matrix,
    on='ModelID',
    how='inner'
)

print(combined_cell_features.shape)

display(combined_cell_features.head())

(92, 274)

,ModelID,0,1,2,3,4,5,6,7,8,...,PIK3CA,ALK,ROS1,MET,ERBB2,NF1,RB1,SMARCA4,CDKN2A,PTEN
0,ACH-000769,0.000000,0.000000,0.000000,2.933871,0.000000,5.080203,0.000000,1.007952,0.000000,...,0,0,0,0,0,0,0,0,1,0
1,ACH-000528,0.000000,0.000000,0.000000,8.689753,0.000000,9.536879,0.000000,3.491262,0.000000,...,0,1,0,0,0,1,0,0,0,0
2,ACH-000585,1.601672,0.000000,1.348526,0.000000,0.195043,1.056408,0.000000,0.000000,0.503666,...,0,0,0,0,0,1,0,1,0,0
3,ACH-000176,7.361752,0.714724,3.704599,0.000000,3.283474,4.789253,0.000000,2.506674,0.699377,...,1,0,0,0,0,0,0,0,0,0
4,ACH-000587,1.381379,0.104786,3.412546,0.000000,1.757902,1.597279,1.692989,2.678646,6.008335,...,1,0,0,0,0,0,0,0,1,0

In [ ]:
combined_cell_features.to_csv(
    "CELL_FEATURES_WITH_MUTATION.csv",
    index=False
)

In [ ]:
#Baseline Models (Creating Dataset embedded together to traing models like xgboost etc)

In [ ]:
from rdkit import Chem

print("RDKit Working")

RDKit Working

In [ ]:
from rdkit import Chem

mol = Chem.MolFromSmiles(
    smiles_df.iloc[0]["CanonicalSMILES"]
)

print(mol)

<rdkit.Chem.rdchem.Mol object at 0x7eee63f61690>

In [ ]:
print(len(smiles_df))
print(smiles_df.columns)

229
Index(['Drug', 'CanonicalSMILES'], dtype='object')

In [ ]:
import torch
print(torch.__version__)
print(torch.version.cuda)
!pip install torch-geometric

2.11.0+cu128
12.8
Collecting torch-geometric
  Downloading torch_geometric-2.7.0-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 5.8 MB/s eta 0:00:00
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.13.5)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2025.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2.0.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.7.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.24.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch-geometric) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (2026.5.20)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->torch-geometric) (4.15.0)
Downloading torch_geometric-2.7.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 39.9 MB/s eta 0:00:00
Installing collected packages: torch-geometric
Successfully installed torch-geometric-2.7.0

In [ ]:
import torch
from torch_geometric.data import Data
from rdkit import Chem

def atom_features(atom):

    return [
        atom.GetAtomicNum(),
        atom.GetDegree(),
        atom.GetFormalCharge(),
        int(atom.GetIsAromatic())
    ]

def smiles_to_graph(smiles):

    mol = Chem.MolFromSmiles(smiles)

    if mol is None:
        return None

    x = []

    for atom in mol.GetAtoms():
        x.append(atom_features(atom))

    x = torch.tensor(
        x,
        dtype=torch.float
    )

    edge_index = []

    for bond in mol.GetBonds():

        start = bond.GetBeginAtomIdx()
        end = bond.GetEndAtomIdx()

        edge_index.append([start,end])
        edge_index.append([end,start])

    edge_index = torch.tensor(
        edge_index,
        dtype=torch.long
    ).t().contiguous()

    return Data(
        x=x,
        edge_index=edge_index
    )


drug_graphs = {}

for _, row in smiles_df.iterrows():

    graph = smiles_to_graph(
        row["CanonicalSMILES"]
    )

    if graph is not None:

        drug_graphs[
            row["Drug"]
        ] = graph

print("Total Graphs:", len(drug_graphs))

Total Graphs: 229

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

from torch_geometric.nn import (
    GCNConv,
    global_mean_pool
)

class DrugGNN(nn.Module):

    def __init__(self):

        super().__init__()

        self.conv1 = GCNConv(
            4,
            64
        )

        self.conv2 = GCNConv(
            64,
            128
        )

        self.conv3 = GCNConv(
            128,
            256
        )

    def forward(self,data):

        x = data.x
        edge_index = data.edge_index

        batch = torch.zeros(
            x.size(0),
            dtype=torch.long,
            device=x.device
        )

        x = self.conv1(
            x,
            edge_index
        )

        x = F.relu(x)

        x = self.conv2(
            x,
            edge_index
        )

        x = F.relu(x)

        x = self.conv3(
            x,
            edge_index
        )

        x = global_mean_pool(
            x,
            batch
        )

        return x

In [ ]:
device = torch.device("cpu")

drug_gnn = DrugGNN().to(device)

drug_gnn.eval()

drug_embeddings = {}

for drug, graph in drug_graphs.items():

    graph = graph.to(device)

    with torch.no_grad():

        emb = drug_gnn(graph)

    drug_embeddings[drug] = (
        emb.cpu()
           .numpy()
           .flatten()
    )

print(
    "Drug Embeddings Created:",
    len(drug_embeddings)
)

Drug Embeddings Created: 229

In [ ]:
drug_emb_df = pd.DataFrame.from_dict(
    drug_embeddings,
    orient="index"
)

drug_emb_df.reset_index(
    inplace=True
)

drug_emb_df.rename(
    columns={
        "index":"DRUG_NAME"
    },
    inplace=True
)

print(drug_emb_df.shape)

display(
    drug_emb_df.head()
)

(229, 257)

,DRUG_NAME,0,1,2,3,4,5,6,7,8,...,246,247,248,249,250,251,252,253,254,255
0,Camptothecin,0.361483,-0.197065,-0.216227,-0.190977,0.098844,-0.315461,0.516459,-0.297235,0.145158,...,-0.255733,0.532546,-0.369383,-0.480347,0.150489,-0.241275,0.219771,-0.281420,0.001854,-0.054600
1,Vinblastine,0.377755,-0.217491,-0.211504,-0.193509,0.074208,-0.297002,0.506364,-0.305388,0.161928,...,-0.261614,0.501015,-0.329500,-0.485237,0.148751,-0.265287,0.242139,-0.259665,0.000278,-0.074902
2,Cisplatin,1.385820,-0.575283,-0.320067,-0.395781,-0.049747,-1.407793,1.815121,-0.759956,0.184787,...,-0.613322,1.455811,-1.359455,-1.358022,0.569415,-1.560773,1.721704,-0.886731,1.115339,-0.332578
3,Cytarabine,0.386006,-0.209440,-0.206126,-0.184910,0.072225,-0.327583,0.535437,-0.298782,0.155874,...,-0.253909,0.518050,-0.355780,-0.490659,0.167129,-0.274682,0.260265,-0.274695,0.015851,-0.064164
4,Docetaxel,0.381571,-0.218496,-0.207215,-0.190474,0.065662,-0.300283,0.511401,-0.302941,0.164039,...,-0.259397,0.495355,-0.325937,-0.484134,0.154152,-0.273249,0.251415,-0.258989,0.004314,-0.075463

In [ ]:
drug_emb_df.to_csv(
    "DRUG_EMBEDDINGS.csv",
    index=False
)

In [ ]:
cell_features = pd.read_csv(
    "/content/CELL_FEATURES_WITH_MUTATION.csv"
)

drug_emb_df = pd.read_csv(
    "/content/DRUG_EMBEDDINGS.csv"
)

gdsc_df = pd.read_csv(
    "/content/FINAL_NSCLC_GDSC.csv"
)

print(cell_features.shape)
print(drug_emb_df.shape)
print(gdsc_df.shape)

(92, 274)
(229, 257)
(26346, 16)

In [ ]:
print(gdsc_df.columns.tolist())

['DATASET', 'NLME_RESULT_ID', 'NLME_CURVE_ID', 'CELL_LINE_NAME', 'SANGER_MODEL_ID', 'CANCER_TYPE', 'DRUG_ID', 'DRUG_NAME', 'PUTATIVE_TARGET', 'PATHWAY_NAME', 'MIN_CONC', 'MAX_CONC', 'LN_IC50', 'AUC', 'RMSE', 'Z_SCORE']

In [ ]:
cancer_emb = pd.read_csv(
    "/content/CANCER_EMBEDDINGS.csv"
)

print(cancer_emb.columns.tolist())

['ModelID', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '176', '177', '178', '179', '180', '181', '182', '183', '184', '185', '186', '187', '188', '189', '190', '191', '192', '193', '194', '195', '196', '197', '198', '199', '200', '201', '202', '203', '204', '205', '206', '207', '208', '209', '210', '211', '212', '213', '214', '215', '216', '217', '218', '219', '220', '221', '222', '223', '224', '225', '226', '227', '228', '229', '230', '231', '232', '233', '234', '235', '236', '237', '238', '239', '240', '241', '242', '243', '244', '245', '246', '247', '248', '249', '250', '251', '252', '253', '254', '255', 'SangerModelID']

In [ ]:
mapping_df = cancer_emb[
    ["ModelID","SangerModelID"]
]

print(mapping_df.shape)

display(mapping_df.head())

(92, 2)

      ModelID SangerModelID
0  ACH-000769     SIDM00548
1  ACH-000528     SIDM00494
2  ACH-000585     SIDM01044
3  ACH-000176     SIDM00341
4  ACH-000587     SIDM00759

In [ ]:
cell_features = pd.read_csv(
    "/content/CELL_FEATURES_WITH_MUTATION.csv"
)

drug_emb_df = pd.read_csv(
    "/content/DRUG_EMBEDDINGS.csv"
)

gdsc_df = pd.read_csv(
    "/content/FINAL_NSCLC_GDSC.csv"
)

mapping_df = cancer_emb[
    ["ModelID","SangerModelID"]
]

training_df = gdsc_df.merge(
    mapping_df,
    left_on="SANGER_MODEL_ID",
    right_on="SangerModelID",
    how="inner"
)

training_df = training_df.merge(
    cell_features,
    on="ModelID",
    how="inner"
)

training_df = training_df.merge(
    drug_emb_df,
    on="DRUG_NAME",
    how="inner"
)

print(training_df.shape)

display(training_df.head())

(19207, 547)

,DATASET,NLME_RESULT_ID,NLME_CURVE_ID,CELL_LINE_NAME,SANGER_MODEL_ID,CANCER_TYPE,DRUG_ID,DRUG_NAME,PUTATIVE_TARGET,PATHWAY_NAME,...,246_y,247_y,248_y,249_y,250_y,251_y,252_y,253_y,254_y,255_y
0,GDSC2,343,15952295,ChaGo-K-1,SIDM00924,Other Solid Cancers,1003,Camptothecin,TOP1,DNA replication,...,-0.255733,0.532546,-0.369383,-0.480347,0.150489,-0.241275,0.219771,-0.28142,0.001854,-0.0546
1,GDSC2,343,15952744,Calu-3,SIDM00922,Non-Small Cell Lung Carcinoma,1003,Camptothecin,TOP1,DNA replication,...,-0.255733,0.532546,-0.369383,-0.480347,0.150489,-0.241275,0.219771,-0.28142,0.001854,-0.0546
2,GDSC2,343,15953026,COR-L23,SIDM00512,Non-Small Cell Lung Carcinoma,1003,Camptothecin,TOP1,DNA replication,...,-0.255733,0.532546,-0.369383,-0.480347,0.150489,-0.241275,0.219771,-0.28142,0.001854,-0.0546
3,GDSC2,343,15953307,LK-2,SIDM00548,Squamous Cell Lung Carcinoma,1003,Camptothecin,TOP1,DNA replication,...,-0.255733,0.532546,-0.369383,-0.480347,0.150489,-0.241275,0.219771,-0.28142,0.001854,-0.0546
4,GDSC2,343,15953588,NCI-H1437,SIDM00734,Non-Small Cell Lung Carcinoma,1003,Camptothecin,TOP1,DNA replication,...,-0.255733,0.532546,-0.369383,-0.480347,0.150489,-0.241275,0.219771,-0.28142,0.001854,-0.0546

In [ ]:
training_df.to_csv(
    "TRAINING_FULL.csv",
    index=False
)

In [ ]:
#| Model           | RMSE | MAE  | R²    | Pearson |
#| --------------- | ---- | ---- | ----- | ------- |
#| Attention Model | 2.20 | 1.79 | 0.376 | 0.672   |

#Previous Best

In [ ]:
from sklearn.model_selection import train_test_split

target = "LN_IC50"

drop_cols = [
    "DATASET",
    "NLME_RESULT_ID",
    "NLME_CURVE_ID",
    "CELL_LINE_NAME",
    "SANGER_MODEL_ID",
    "CANCER_TYPE",
    "DRUG_ID",
    "DRUG_NAME",
    "PUTATIVE_TARGET",
    "PATHWAY_NAME",
    "MIN_CONC",
    "MAX_CONC",
    "AUC",
    "RMSE",
    "Z_SCORE",
    "ModelID",
    "SangerModelID"
]

X = training_df.drop(
    columns=drop_cols + [target],
    errors="ignore"
)

y = training_df[target]

print("X Shape:", X.shape)
print("y Shape:", y.shape)

X Shape: (19207, 530)
y Shape: (19207,)

In [ ]:
#Baseline Model 1 — Linear Regression

In [ ]:
X = X.drop(
    columns=[
        "SangerModelID_x",
        "SangerModelID_y"
    ],
    errors="ignore"
)

print(X.shape)

(19207, 528)

In [ ]:
print(X.dtypes[X.dtypes == "object"])

Series([], dtype: object)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train, y_train)

pred_lr = lr.predict(X_test)

print("Linear Regression Trained")

Linear Regression Trained

In [ ]:
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

from scipy.stats import pearsonr
import numpy as np

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        pred_lr
    )
)

mae = mean_absolute_error(
    y_test,
    pred_lr
)

r2 = r2_score(
    y_test,
    pred_lr
)

pearson = pearsonr(
    y_test,
    pred_lr
)[0]

print("RMSE:", rmse)
print("MAE:", mae)
print("R2:", r2)
print("Pearson:", pearson)

RMSE: 1.1849508283613681
MAE: 0.8928168897186352
R2: 0.8193829102901078
Pearson: 0.9052414050454266

In [ ]:
#Model 2: Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=20,
    random_state=42,
    n_jobs=-1
)

rf.fit(
    X_train,
    y_train
)

pred_rf = rf.predict(X_test)

print("Random Forest Trained")

Random Forest Trained

In [ ]:
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

from scipy.stats import pearsonr
import numpy as np

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        pred_rf
    )
)

mae = mean_absolute_error(
    y_test,
    pred_rf
)

r2 = r2_score(
    y_test,
    pred_rf
)

pearson = pearsonr(
    y_test,
    pred_rf
)[0]

print("RMSE:", rmse)
print("MAE:", mae)
print("R2:", r2)
print("Pearson:", pearson)

RMSE: 1.2021247208067245
MAE: 0.9132594287921222
R2: 0.814109481505322
Pearson: 0.9025625231615507

In [ ]:
#Model 3: XG Boost

In [ ]:
import xgboost as xgb

print(xgb.__version__)

3.2.0

In [ ]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=300,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(
    X_train,
    y_train
)

pred_xgb = xgb_model.predict(X_test)

print("XGBoost Trained")

XGBoost Trained

In [ ]:
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

from scipy.stats import pearsonr
import numpy as np

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        pred_xgb
    )
)

mae = mean_absolute_error(
    y_test,
    pred_xgb
)

r2 = r2_score(
    y_test,
    pred_xgb
)

pearson = pearsonr(
    y_test,
    pred_xgb
)[0]

print("RMSE:", rmse)
print("MAE:", mae)
print("R2:", r2)
print("Pearson:", pearson)

RMSE: 1.1144855795093154
MAE: 0.8512913529639978
R2: 0.8402256390032615
Pearson: 0.9168906630522421

In [ ]:
import pandas as pd

baseline_results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest",
        "XGBoost"
    ],
    "RMSE": [
        1.1849508298062343,
        1.1935026018833028,
        1.1339143744476925
    ],
    "MAE": [
        0.8928168923737051,
        0.9097281964998793,
        0.8645345112896898
    ],
    "R2": [
        0.819382909849638,
        0.8167664808590511,
        0.8346063985727934
    ],
    "Pearson": [
        0.9052414048395562,
        0.9038853794532068,
        0.9137746474197841
    ]
})

print(baseline_results)

baseline_results.to_csv(
    "baseline_results.csv",
    index=False
)

print("\n✅ baseline_results.csv saved successfully")

               Model      RMSE       MAE        R2   Pearson
0  Linear Regression  1.184951  0.892817  0.819383  0.905241
1      Random Forest  1.193503  0.909728  0.816766  0.903885
2            XGBoost  1.133914  0.864535  0.834606  0.913775

✅ baseline_results.csv saved successfully

In [ ]:
#Attention Ablation Study

In [ ]:
import numpy as np

cell_cols = [f"{i}_x" for i in range(256)]
drug_cols = [f"{i}_y" for i in range(256)]

X_cell = training_df[cell_cols].values
X_drug = training_df[drug_cols].values

y = training_df["LN_IC50"].values

print(X_cell.shape)
print(X_drug.shape)
print(y.shape)

(19207, 256)
(19207, 256)
(19207,)

In [ ]:
from sklearn.model_selection import train_test_split

(
    X_cell_train,
    X_cell_test,
    X_drug_train,
    X_drug_test,
    y_train,
    y_test
) = train_test_split(
    X_cell,
    X_drug,
    y,
    test_size=0.2,
    random_state=42
)

print(X_cell_train.shape)
print(X_drug_train.shape)

(15365, 256)
(15365, 256)

In [ ]:
# NO ATTENTION MODEL:

from tensorflow.keras.layers import (
    Input,
    Dense,
    Concatenate,
    Dropout
)

from tensorflow.keras.models import Model

cell_input = Input(
    shape=(256,),
    name="CancerEmbedding"
)

drug_input = Input(
    shape=(256,),
    name="DrugEmbedding"
)

merged = Concatenate()(
    [
        cell_input,
        drug_input
    ]
)

x = Dense(
    512,
    activation="relu"
)(merged)

x = Dropout(0.3)(x)

x = Dense(
    256,
    activation="relu"
)(x)

x = Dropout(0.3)(x)

x = Dense(
    128,
    activation="relu"
)(x)

output = Dense(
    1,
    name="LN_IC50"
)(x)

no_attention_model = Model(
    inputs=[
        cell_input,
        drug_input
    ],
    outputs=output
)

no_attention_model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

no_attention_model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ CancerEmbedding     │ (None, 256)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ DrugEmbedding       │ (None, 256)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 512)       │          0 │ CancerEmbedding[… │
│ (Concatenate)       │                   │            │ DrugEmbedding[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 512)       │    262,656 │ concatenate[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_2 (Dropout) │ (None, 512)       │          0 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 256)       │    131,328 │ dropout_2[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_3 (Dropout) │ (None, 256)       │          0 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 128)       │     32,896 │ dropout_3[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ LN_IC50 (Dense)     │ (None, 1)         │        129 │ dense_2[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 427,009 (1.63 MB)

 Trainable params: 427,009 (1.63 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = no_attention_model.fit(
    [
        X_cell_train,
        X_drug_train
    ],
    y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=128,
    verbose=1
)

Epoch 1/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - loss: 7.9268 - mae: 2.1771 - val_loss: 8.0152 - val_mae: 2.2823
Epoch 2/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3816 - mae: 2.0984 - val_loss: 7.9465 - val_mae: 2.2747
Epoch 3/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2707 - mae: 2.0809 - val_loss: 7.8937 - val_mae: 2.2669
Epoch 4/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2434 - mae: 2.0719 - val_loss: 7.4667 - val_mae: 2.1192
Epoch 5/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.2379 - mae: 2.0696 - val_loss: 7.8684 - val_mae: 2.2599
Epoch 6/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1971 - mae: 2.0693 - val_loss: 7.5367 - val_mae: 2.1703
Epoch 7/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1872 - mae: 2.0609 - val_loss: 7.5671 - val_mae: 2.1835
Epoch 8/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0965 - mae: 2.0455 - val_loss: 7.5650 - val_mae: 2.1805
Epoch 9/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0773 - mae: 2.0411 - val_loss: 7.9670 - val_mae: 2.2838
Epoch 10/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0648 - mae: 2.0398 - val_loss: 7.5458 - val_mae: 2.1693
Epoch 11/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0425 - mae: 2.0395 - val_loss: 7.3432 - val_mae: 2.0531
Epoch 12/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.1610 - mae: 2.0584 - val_loss: 7.7333 - val_mae: 2.2306
Epoch 13/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7.0116 - mae: 2.0319 - val_loss: 7.7206 - val_mae: 2.2269
Epoch 14/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 6.9996 - mae: 2.0328 - val_loss: 7.3938 - val_mae: 2.0275
Epoch 15/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 7.1533 - mae: 2.0545 - val_loss: 7.5216 - val_mae: 2.1747
Epoch 16/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9928 - mae: 2.0308 - val_loss: 7.7235 - val_mae: 2.2288
Epoch 17/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9592 - mae: 2.0224 - val_loss: 7.6397 - val_mae: 2.2117
Epoch 18/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.0053 - mae: 2.0326 - val_loss: 7.7058 - val_mae: 2.2293
Epoch 19/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9708 - mae: 2.0245 - val_loss: 7.3502 - val_mae: 2.1254
Epoch 20/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9213 - mae: 2.0184 - val_loss: 8.0167 - val_mae: 2.3001
Epoch 21/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9805 - mae: 2.0273 - val_loss: 7.6396 - val_mae: 2.2050
Epoch 22/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9361 - mae: 2.0164 - val_loss: 7.3617 - val_mae: 2.1339
Epoch 23/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9722 - mae: 2.0243 - val_loss: 7.7891 - val_mae: 2.2511
Epoch 24/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9470 - mae: 2.0260 - val_loss: 7.3916 - val_mae: 2.1431
Epoch 25/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8802 - mae: 2.0120 - val_loss: 7.4140 - val_mae: 2.1452
Epoch 26/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.9192 - mae: 2.0172 - val_loss: 7.4024 - val_mae: 2.1494
Epoch 27/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8882 - mae: 2.0134 - val_loss: 7.3987 - val_mae: 2.1502
Epoch 28/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9109 - mae: 2.0149 - val_loss: 7.4513 - val_mae: 2.1671
Epoch 29/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8636 - mae: 2.0047 - val_loss: 7.6910 - val_mae: 2.2315
Epoch 30/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8641 - mae: 2.0086 - val_loss: 7.3566 - val_mae: 2.1383
Epoch 31/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9303 - mae: 2.0151 - val_loss: 7.5382 - val_mae: 2.1930
Epoch 32/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8762 - mae: 2.0095 - val_loss: 7.4777 - val_mae: 2.1726
Epoch 33/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9154 - mae: 2.0170 - val_loss: 7.4039 - val_mae: 2.1501
Epoch 34/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8468 - mae: 2.0082 - val_loss: 7.3839 - val_mae: 2.1474
Epoch 35/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8712 - mae: 2.0095 - val_loss: 7.5432 - val_mae: 2.1839
Epoch 36/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8746 - mae: 2.0091 - val_loss: 7.5782 - val_mae: 2.1998
Epoch 37/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8292 - mae: 2.0009 - val_loss: 7.8261 - val_mae: 2.2604
Epoch 38/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8395 - mae: 2.0046 - val_loss: 7.8200 - val_mae: 2.2573
Epoch 39/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.8564 - mae: 2.0101 - val_loss: 7.6797 - val_mae: 2.2260
Epoch 40/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.7987 - mae: 1.9986 - val_loss: 7.3842 - val_mae: 2.1457
Epoch 41/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.7912 - mae: 1.9935 - val_loss: 7.3530 - val_mae: 2.1382
Epoch 42/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.8115 - mae: 2.0012 - val_loss: 7.5280 - val_mae: 2.1845
Epoch 43/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 6.8167 - mae: 1.9951 - val_loss: 7.8564 - val_mae: 2.2716
Epoch 44/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.7833 - mae: 1.9957 - val_loss: 7.5305 - val_mae: 2.1891
Epoch 45/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8166 - mae: 2.0027 - val_loss: 7.5089 - val_mae: 2.1857
Epoch 46/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8332 - mae: 2.0062 - val_loss: 7.5521 - val_mae: 2.1923
Epoch 47/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.7767 - mae: 1.9923 - val_loss: 7.6683 - val_mae: 2.2265
Epoch 48/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.7645 - mae: 1.9932 - val_loss: 7.8809 - val_mae: 2.2775
Epoch 49/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8069 - mae: 2.0049 - val_loss: 7.7599 - val_mae: 2.2498
Epoch 50/50
97/97 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.7753 - mae: 1.9941 - val_loss: 7.8183 - val_mae: 2.2622

In [ ]:
pred = no_attention_model.predict(
    [
        X_cell_test,
        X_drug_test
    ]
)

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

from scipy.stats import pearsonr

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        pred
    )
)

mae = mean_absolute_error(
    y_test,
    pred
)

r2 = r2_score(
    y_test,
    pred
)

pearson = pearsonr(
    y_test.flatten(),
    pred.flatten()
)[0]

print("RMSE:", rmse)
print("MAE:", mae)
print("R2:", r2)
print("Pearson:", pearson)

121/121 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
RMSE: 2.7592992471500186
MAE: 2.244729224526651
R2: 0.020609725036548676
Pearson: 0.3441448826128339

In [ ]:
import pandas as pd

attention_ablation = pd.DataFrame({
    "Model": [
        "Without Attention",
        "With Attention"
    ],
    "RMSE": [
        2.661,
        2.203
    ],
    "MAE": [
        2.116,
        1.792
    ],
    "R2": [
        0.089,
        0.376
    ],
    "Pearson": [
        0.353,
        0.672
    ]
})

attention_ablation.to_csv(
    "attention_ablation_results.csv",
    index=False
)

attention_ablation

               Model   RMSE    MAE     R2  Pearson
0  Without Attention  2.661  2.116  0.089    0.353
1     With Attention  2.203  1.792  0.376    0.672

In [ ]:
#Proper encoder with trained IC50

In [ ]:
cell_ic50 = (
    training_df
    .groupby("SangerModelID_x")["LN_IC50"]
    .mean()
    .reset_index()
)

print(cell_ic50.shape)
cell_ic50.head()

(92, 2)

  SangerModelID_x   LN_IC50
0       SIDM00046  3.685702
1       SIDM00116  3.136966
2       SIDM00117  2.669279
3       SIDM00119  4.227531
4       SIDM00133  3.586543

In [ ]:
cell_mapping = training_df[
    ["ModelID", "SangerModelID_x"]
].drop_duplicates()

print(cell_mapping.shape)
cell_mapping.head()

(92, 2)

      ModelID SangerModelID_x
0  ACH-000867       SIDM00924
1  ACH-000392       SIDM00922
2  ACH-000662       SIDM00512
3  ACH-000769       SIDM00548
4  ACH-000589       SIDM00734

In [ ]:
# Expression Data
NSCLC_expression_scaled = pd.read_csv('/content/NSCLC_expression_scaled.csv')
expr = NSCLC_expression_scaled.copy()

# Merge Cell Mapping

expr = expr.merge(
    cell_mapping,
    on="ModelID",
    how="inner"
)

# Merge Mean IC50

task_df = expr.merge(
    cell_ic50,
    on="SangerModelID_x",
    how="inner"
)

print(task_df.shape)

task_df.head()

(92, 8149)

,ModelID,TSPAN6 (7105),CFH (3075),FUCA2 (2519),GCLC (2729),NIPAL3 (57185),LAS1L (81887),ENPP4 (22875),SEMA3F (6405),CFTR (1080),...,ASDURF (110599588),NOTCH2NLR (101929796),DERPC (113455421),NOTCH2NLC (100996717),H3C2 (8358),NPBWR1 (2831),F8A2 (474383),F8A1 (8263),SangerModelID_x,LN_IC50
0,ACH-000769,0.720820,-1.159283,0.004505,0.016968,-0.310588,-0.232841,0.173370,-0.548671,0.286691,...,-0.563779,3.022382,0.277748,1.366609,-0.398641,0.138544,0.101572,-0.386293,SIDM00548,2.949896
1,ACH-000528,0.428517,-0.734930,0.883446,-1.075298,0.502380,-0.152433,1.574718,0.869558,-0.318270,...,0.339073,0.925263,-1.126724,-0.356900,-0.007251,-0.583486,-0.757256,0.743182,SIDM00494,3.286264
2,ACH-000585,-1.030152,-1.206121,-0.735052,-1.659157,-0.116595,-0.098581,-0.828102,-1.036255,-0.270486,...,-0.125519,0.094701,0.238198,-0.327235,-0.376397,2.336479,-0.757256,0.388168,SIDM01044,2.342288
3,ACH-000176,-2.769692,-0.890577,1.173685,-1.008168,1.113241,-0.224587,-1.646554,-0.434372,-0.354862,...,-0.355857,0.876574,-0.139668,1.056228,0.352325,-0.618886,-0.757256,0.359048,SIDM00341,2.953704
4,ACH-000587,0.301215,-0.717777,0.474786,-0.840215,-0.370862,1.260220,-1.346821,0.496600,-0.290216,...,0.890767,0.373962,0.660877,-0.570693,1.277509,0.351061,-0.757256,0.425892,SIDM00759,2.665550

In [ ]:
import numpy as np

gene_cols = NSCLC_expression_scaled.columns[1:]

X_gene = task_df[gene_cols].values

y_ic50 = task_df["LN_IC50"].values

print(X_gene.shape)
print(y_ic50.shape)

(92, 8146)
(92,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_gene,
    y_ic50,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(73, 8146)
(19, 8146)

In [ ]:
from tensorflow.keras.layers import (
    Input,
    Dense,
    BatchNormalization,
    Dropout
)

from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

input_layer = Input(
    shape=(8146,),
    name="GeneInput"
)

# Encoder

x = Dense(
    2048,
    activation="relu"
)(input_layer)

x = BatchNormalization()(x)

x = Dropout(0.3)(x)

x = Dense(
    1024,
    activation="relu"
)(x)

x = BatchNormalization()(x)

x = Dropout(0.3)(x)

x = Dense(
    512,
    activation="relu"
)(x)

latent = Dense(
    256,
    activation="relu",
    name="LatentEmbedding"
)(x)

# Decoder

d = Dense(
    512,
    activation="relu"
)(latent)

d = Dense(
    1024,
    activation="relu"
)(d)

d = Dense(
    2048,
    activation="relu"
)(d)

reconstruction = Dense(
    8146,
    name="Reconstruction"
)(d)

# IC50 Prediction Head

p = Dense(
    128,
    activation="relu"
)(latent)

p = Dense(
    64,
    activation="relu"
)(p)

ic50_output = Dense(
    1,
    name="IC50Prediction"
)(p)

task_autoencoder = Model(
    inputs=input_layer,
    outputs=[
        reconstruction,
        ic50_output
    ]
)

task_autoencoder.compile(
    optimizer=Adam(1e-4),
    loss={
        "Reconstruction":"mse",
        "IC50Prediction":"mse"
    },
    loss_weights={
        "Reconstruction":1.0,
        "IC50Prediction":5.0
    }
)

task_autoencoder.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ GeneInput           │ (None, 8146)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 2048)      │ 16,685,056 │ GeneInput[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 2048)      │      8,192 │ dense_3[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_4 (Dropout) │ (None, 2048)      │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 1024)      │  2,098,176 │ dropout_4[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 1024)      │      4,096 │ dense_4[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_5 (Dropout) │ (None, 1024)      │          0 │ batch_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 512)       │    524,800 │ dropout_5[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ LatentEmbedding     │ (None, 256)       │    131,328 │ dense_5[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_6 (Dense)     │ (None, 512)       │    131,584 │ LatentEmbedding[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_7 (Dense)     │ (None, 1024)      │    525,312 │ dense_6[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_9 (Dense)     │ (None, 128)       │     32,896 │ LatentEmbedding[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_8 (Dense)     │ (None, 2048)      │  2,099,200 │ dense_7[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_10 (Dense)    │ (None, 64)        │      8,256 │ dense_9[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Reconstruction      │ (None, 8146)      │ 16,691,154 │ dense_8[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ IC50Prediction      │ (None, 1)         │         65 │ dense_10[0][0]    │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 38,940,115 (148.54 MB)

 Trainable params: 38,933,971 (148.52 MB)

 Non-trainable params: 6,144 (24.00 KB)

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=15,
    restore_best_weights=True
)

history = task_autoencoder.fit(
    X_train,
    {
        "Reconstruction":X_train,
        "IC50Prediction":y_train
    },
    validation_data=(
        X_test,
        {
            "Reconstruction":X_test,
            "IC50Prediction":y_test
        }
    ),
    epochs=200,
    batch_size=16,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 13s 1s/step - IC50Prediction_loss: 5.9085 - Reconstruction_loss: 0.9454 - loss: 31.3918 - val_IC50Prediction_loss: 5.7348 - val_Reconstruction_loss: 1.1468 - val_loss: 27.4059
Epoch 2/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - IC50Prediction_loss: 1.7869 - Reconstruction_loss: 0.9429 - loss: 10.3901 - val_IC50Prediction_loss: 3.5711 - val_Reconstruction_loss: 1.1473 - val_loss: 15.8011
Epoch 3/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - IC50Prediction_loss: 0.7068 - Reconstruction_loss: 0.9261 - loss: 4.3908 - val_IC50Prediction_loss: 2.5691 - val_Reconstruction_loss: 1.1471 - val_loss: 10.2312
Epoch 4/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - IC50Prediction_loss: 0.6941 - Reconstruction_loss: 0.9336 - loss: 4.4430 - val_IC50Prediction_loss: 2.5446 - val_Reconstruction_loss: 1.1468 - val_loss: 10.1138
Epoch 5/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - IC50Prediction_loss: 0.6814 - Reconstruction_loss: 0.9289 - loss: 4.4694 - val_IC50Prediction_loss: 2.9461 - val_Reconstruction_loss: 1.1467 - val_loss: 12.6912
Epoch 6/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - IC50Prediction_loss: 0.3754 - Reconstruction_loss: 0.9252 - loss: 2.8637 - val_IC50Prediction_loss: 3.3926 - val_Reconstruction_loss: 1.1457 - val_loss: 15.3729
Epoch 7/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - IC50Prediction_loss: 0.2769 - Reconstruction_loss: 0.9156 - loss: 2.3650 - val_IC50Prediction_loss: 3.4395 - val_Reconstruction_loss: 1.1444 - val_loss: 15.9285
Epoch 8/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - IC50Prediction_loss: 0.4242 - Reconstruction_loss: 0.9157 - loss: 3.0227 - val_IC50Prediction_loss: 3.3086 - val_Reconstruction_loss: 1.1422 - val_loss: 15.2845
Epoch 9/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - IC50Prediction_loss: 0.3483 - Reconstruction_loss: 0.9127 - loss: 2.5360 - val_IC50Prediction_loss: 3.0723 - val_Reconstruction_loss: 1.1375 - val_loss: 13.9188
Epoch 10/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - IC50Prediction_loss: 0.2673 - Reconstruction_loss: 0.8952 - loss: 2.2293 - val_IC50Prediction_loss: 2.8660 - val_Reconstruction_loss: 1.1266 - val_loss: 12.7630
Epoch 11/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - IC50Prediction_loss: 0.3898 - Reconstruction_loss: 0.9001 - loss: 2.7603 - val_IC50Prediction_loss: 2.9625 - val_Reconstruction_loss: 1.1120 - val_loss: 13.1823
Epoch 12/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - IC50Prediction_loss: 0.3153 - Reconstruction_loss: 0.8804 - loss: 2.3812 - val_IC50Prediction_loss: 3.0820 - val_Reconstruction_loss: 1.0909 - val_loss: 13.8490
Epoch 13/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - IC50Prediction_loss: 0.2846 - Reconstruction_loss: 0.8652 - loss: 2.2368 - val_IC50Prediction_loss: 3.0743 - val_Reconstruction_loss: 1.0676 - val_loss: 13.7477
Epoch 14/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - IC50Prediction_loss: 0.3321 - Reconstruction_loss: 0.8595 - loss: 2.4637 - val_IC50Prediction_loss: 2.9346 - val_Reconstruction_loss: 1.0395 - val_loss: 13.0658
Epoch 15/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - IC50Prediction_loss: 0.2128 - Reconstruction_loss: 0.8486 - loss: 1.9524 - val_IC50Prediction_loss: 2.9082 - val_Reconstruction_loss: 1.0219 - val_loss: 13.1492
Epoch 16/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - IC50Prediction_loss: 0.2526 - Reconstruction_loss: 0.8053 - loss: 2.0857 - val_IC50Prediction_loss: 2.9256 - val_Reconstruction_loss: 1.0008 - val_loss: 13.3755
Epoch 17/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - IC50Prediction_loss: 0.2194 - Reconstruction_loss: 0.8174 - loss: 1.8964 - val_IC50Prediction_loss: 2.9738 - val_Reconstruction_loss: 0.9882 - val_loss: 13.5198
Epoch 18/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - IC50Prediction_loss: 0.2446 - Reconstruction_loss: 0.8054 - loss: 1.9572 - val_IC50Prediction_loss: 2.9892 - val_Reconstruction_loss: 0.9790 - val_loss: 13.4320
Epoch 19/200
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - IC50Prediction_loss: 0.2435 - Reconstruction_loss: 0.7666 - loss: 1.9489 - val_IC50Prediction_loss: 2.9346 - val_Reconstruction_loss: 0.9640 - val_loss: 13.1034

In [ ]:
history.history.keys()

dict_keys(['IC50Prediction_loss', 'Reconstruction_loss', 'loss', 'val_IC50Prediction_loss', 'val_Reconstruction_loss', 'val_loss'])

In [ ]:
from tensorflow.keras.models import Model

task_encoder = Model(
    inputs=task_autoencoder.input,
    outputs=task_autoencoder.get_layer(
        "LatentEmbedding"
    ).output
)

task_encoder.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ GeneInput (InputLayer)          │ (None, 8146)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 2048)           │    16,685,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 2048)           │         8,192 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1024)           │     2,098,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 1024)           │         4,096 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 1024)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 512)            │       524,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ LatentEmbedding (Dense)         │ (None, 256)            │       131,328 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,451,648 (74.20 MB)

 Trainable params: 19,445,504 (74.18 MB)

 Non-trainable params: 6,144 (24.00 KB)

In [ ]:
task_autoencoder.save(
    "task_aware_autoencoder.keras"
)

task_encoder.save(
    "task_aware_encoder.keras"
)

print("Saved Successfully")

Saved Successfully

In [ ]:
X_gene_all = task_df[gene_cols].values

task_embeddings = task_encoder.predict(
    X_gene_all
)

print(task_embeddings.shape)

3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 209ms/step
(92, 256)

In [ ]:
import pandas as pd

task_embedding_df = pd.DataFrame(
    task_embeddings
)

task_embedding_df.insert(
    0,
    "ModelID",
    task_df["ModelID"].values
)

task_embedding_df.head()

,ModelID,0,1,2,3,4,5,6,7,8,...,246,247,248,249,250,251,252,253,254,255
0,ACH-000769,0.130234,0.000000,0.000000,0.976543,0.0,0.000000,1.669606,0.291935,0.000000,...,0.0,1.234325,1.559797,0.815059,0.326858,2.087811,0.594893,0.055000,0.000000,0.177164
1,ACH-000528,0.603273,1.044294,0.000000,0.000000,0.0,0.240411,1.687555,0.044271,0.000000,...,0.0,1.490912,0.667807,0.268658,0.000000,1.336857,0.000000,0.722962,0.109287,2.026680
2,ACH-000585,0.050205,0.000000,0.000000,0.226873,0.0,0.496220,0.726164,0.985220,0.455805,...,0.0,1.152993,1.475829,0.313568,0.301355,1.424867,0.000000,0.000000,0.000000,0.000000
3,ACH-000176,0.000000,0.000000,0.122873,0.000000,0.0,0.000000,0.567646,0.584774,0.232363,...,0.0,0.700183,0.938498,0.000000,0.931514,1.270821,0.453772,0.000000,0.269090,0.329383
4,ACH-000587,0.360172,0.000000,0.000000,0.000000,0.0,0.000000,1.394738,1.188975,0.000000,...,0.0,0.852915,0.443308,0.232105,0.000000,0.645106,0.000000,0.000000,0.000000,0.846615

In [ ]:
task_embedding_df.to_csv(
    "TASK_AWARE_CANCER_EMBEDDINGS.csv",
    index=False
)

print("Saved")

Saved

In [ ]:
task_cell_features = task_embedding_df.merge(
    mutation_matrix,
    on="ModelID",
    how="inner"
)

print(task_cell_features.shape)

task_cell_features.head()

(92, 273)

,ModelID,0,1,2,3,4,5,6,7,8,...,PIK3CA,ALK,ROS1,MET,ERBB2,NF1,RB1,SMARCA4,CDKN2A,PTEN
0,ACH-000769,0.130234,0.000000,0.000000,0.976543,0.0,0.000000,1.669606,0.291935,0.000000,...,0,0,0,0,0,0,0,0,1,0
1,ACH-000528,0.603273,1.044294,0.000000,0.000000,0.0,0.240411,1.687555,0.044271,0.000000,...,0,1,0,0,0,1,0,0,0,0
2,ACH-000585,0.050205,0.000000,0.000000,0.226873,0.0,0.496220,0.726164,0.985220,0.455805,...,0,0,0,0,0,1,0,1,0,0
3,ACH-000176,0.000000,0.000000,0.122873,0.000000,0.0,0.000000,0.567646,0.584774,0.232363,...,1,0,0,0,0,0,0,0,0,0
4,ACH-000587,0.360172,0.000000,0.000000,0.000000,0.0,0.000000,1.394738,1.188975,0.000000,...,1,0,0,0,0,0,0,0,1,0

In [ ]:
task_cell_features.to_csv(
    "TASK_AWARE_CELL_FEATURES.csv",
    index=False
)

In [ ]:
task_cell_features = task_cell_features.merge(
    cell_mapping,
    on="ModelID",
    how="left"
)

print(task_cell_features.shape)

(92, 274)

In [ ]:
training_task = gdsc_df.merge(
    task_cell_features,
    left_on="SANGER_MODEL_ID",
    right_on="SangerModelID_x",
    how="inner"
)

print(training_task.shape)
drug_embeddings_df = pd.read_csv('/content/DRUG_EMBEDDINGS.csv')

(23281, 290)

In [ ]:
training_task = gdsc_df.merge(
    task_cell_features,
    left_on="SANGER_MODEL_ID",
    right_on="SangerModelID_x",
    how="inner"
)

training_task = training_task.merge(
    drug_embeddings_df,
    on="DRUG_NAME",
    how="inner",
    suffixes=("_cell", "_drug")
)

print(training_task.shape)

(19207, 546)

In [ ]:
# Rename cell embeddings

cell_cols = list(range(256))

rename_cell = {
    i: f"cell_{i}"
    for i in cell_cols
}

training_task = training_task.rename(
    columns=rename_cell
)

print("Cell columns renamed")

Cell columns renamed

In [ ]:
print(training_task.columns[15:25])

Index(['Z_SCORE', 'ModelID', 'cell_0', 'cell_1', 'cell_2', 'cell_3', 'cell_4',
       'cell_5', 'cell_6', 'cell_7'],
      dtype='object')

In [ ]:
drug_cols = [
    col for col in training_task.columns
    if isinstance(col, str)
    and col.isdigit()
]

print(len(drug_cols))
print(drug_cols[:5])
print(drug_cols[-5:])

256
['0', '1', '2', '3', '4']
['251', '252', '253', '254', '255']

In [ ]:
rename_drug = {
    col: f"drug_{col}"
    for col in drug_cols
}

training_task = training_task.rename(
    columns=rename_drug
)

print("Drug columns renamed")

Drug columns renamed

In [ ]:
print(training_task.columns[15:25])

print(training_task.columns[270:290])

print(training_task.columns[-10:])

Index(['Z_SCORE', 'ModelID', 'cell_0', 'cell_1', 'cell_2', 'cell_3', 'cell_4',
       'cell_5', 'cell_6', 'cell_7'],
      dtype='object')
Index(['cell_253', 'cell_254', 'cell_255', 'TP53', 'EGFR', 'KRAS', 'STK11',
       'KEAP1', 'BRAF', 'PIK3CA', 'ALK', 'ROS1', 'MET', 'ERBB2', 'NF1', 'RB1',
       'SMARCA4', 'CDKN2A', 'PTEN', 'SangerModelID_x'],
      dtype='object')
Index(['drug_246', 'drug_247', 'drug_248', 'drug_249', 'drug_250', 'drug_251',
       'drug_252', 'drug_253', 'drug_254', 'drug_255'],
      dtype='object')

In [ ]:
training_task.to_csv(
    "TRAINING_FULL_TASK_AWARE.csv",
    index=False
)
print("Saved")

Saved

In [ ]:
from google.colab import files

# Trigger the browser download
files.download("TRAINING_FULL_TASK_AWARE.csv")

In [ ]:
cell_cols = [f"cell_{i}" for i in range(256)]

mutation_cols = [
    "TP53","EGFR","KRAS","STK11",
    "KEAP1","BRAF","PIK3CA","ALK",
    "ROS1","MET","ERBB2","NF1",
    "RB1","SMARCA4","CDKN2A","PTEN"
]

drug_cols = [f"drug_{i}" for i in range(256)]

X_cell = training_task[
    cell_cols + mutation_cols
].values

X_drug = training_task[
    drug_cols
].values

y = training_task["LN_IC50"].values

print(X_cell.shape)
print(X_drug.shape)
print(y.shape)

(19207, 272)
(19207, 256)
(19207,)

In [ ]:
from sklearn.model_selection import train_test_split

(
    X_cell_train,
    X_cell_test,
    X_drug_train,
    X_drug_test,
    y_train,
    y_test
) = train_test_split(
    X_cell,
    X_drug,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from tensorflow.keras.layers import (
    Input,
    Dense,
    Dropout,
    Concatenate,
    Reshape,
    Flatten,
    MultiHeadAttention,
    LayerNormalization
)

from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

cell_input = Input(
    shape=(272,),
    name="CellInput"
)

cell_proj = Dense(
    256,
    activation="relu"
)(cell_input)

drug_input = Input(
    shape=(256,),
    name="DrugInput"
)

cell_seq = Reshape((1,256))(cell_proj)
drug_seq = Reshape((1,256))(drug_input)

attn1 = MultiHeadAttention(
    num_heads=4,
    key_dim=64
)(
    cell_seq,
    drug_seq
)

attn1 = LayerNormalization()(attn1)

attn2 = MultiHeadAttention(
    num_heads=4,
    key_dim=64
)(
    drug_seq,
    cell_seq
)

attn2 = LayerNormalization()(attn2)

attn1 = Flatten()(attn1)
attn2 = Flatten()(attn2)

merged = Concatenate()([
    cell_proj,
    drug_input,
    attn1,
    attn2
])

x = Dense(
    512,
    activation="relu"
)(merged)

x = Dropout(0.3)(x)

x = Dense(
    256,
    activation="relu"
)(x)

x = Dropout(0.3)(x)

x = Dense(
    128,
    activation="relu"
)(x)

output = Dense(
    1,
    name="LN_IC50"
)(x)

final_attention_model = Model(
    inputs=[
        cell_input,
        drug_input
    ],
    outputs=output
)

final_attention_model.compile(
    optimizer=Adam(
        learning_rate=1e-4
    ),
    loss="mse",
    metrics=["mae"]
)

final_attention_model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ CellInput           │ (None, 272)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_11 (Dense)    │ (None, 256)       │     69,888 │ CellInput[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ DrugInput           │ (None, 256)       │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ reshape (Reshape)   │ (None, 1, 256)    │          0 │ dense_11[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ reshape_1 (Reshape) │ (None, 1, 256)    │          0 │ DrugInput[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 1, 256)    │    263,168 │ reshape[0][0],    │
│ (MultiHeadAttentio… │                   │            │ reshape_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 1, 256)    │    263,168 │ reshape_1[0][0],  │
│ (MultiHeadAttentio… │                   │            │ reshape[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalization │ (None, 1, 256)    │        512 │ multi_head_atten… │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_normalizatio… │ (None, 1, 256)    │        512 │ multi_head_atten… │
│ (LayerNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 256)       │          0 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_1 (Flatten) │ (None, 256)       │          0 │ layer_normalizat… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_1       │ (None, 1024)      │          0 │ dense_11[0][0],   │
│ (Concatenate)       │                   │            │ DrugInput[0][0],  │
│                     │                   │            │ flatten[0][0],    │
│                     │                   │            │ flatten_1[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_12 (Dense)    │ (None, 512)       │    524,800 │ concatenate_1[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_8 (Dropout) │ (None, 512)       │          0 │ dense_12[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_13 (Dense)    │ (None, 256)       │    131,328 │ dropout_8[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_9 (Dropout) │ (None, 256)       │          0 │ dense_13[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_14 (Dense)    │ (None, 128)       │     32,896 │ dropout_9[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ LN_IC50 (Dense)     │ (None, 1)         │        129 │ dense_14[0][0]    │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 1,286,401 (4.91 MB)

 Trainable params: 1,286,401 (4.91 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

history = final_attention_model.fit(
    [
        X_cell_train,
        X_drug_train
    ],
    y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=128,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 14s 67ms/step - loss: 7.5868 - mae: 2.1222 - val_loss: 7.3661 - val_mae: 2.1204
Epoch 2/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7.1906 - mae: 2.0604 - val_loss: 7.1414 - val_mae: 2.0458
Epoch 3/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.9913 - mae: 2.0334 - val_loss: 7.3241 - val_mae: 2.1486
Epoch 4/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.8559 - mae: 2.0160 - val_loss: 7.3099 - val_mae: 2.1464
Epoch 5/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.9078 - mae: 2.0222 - val_loss: 7.0970 - val_mae: 2.1064
Epoch 6/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.6932 - mae: 1.9922 - val_loss: 6.7154 - val_mae: 1.9501
Epoch 7/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.6798 - mae: 1.9912 - val_loss: 6.9861 - val_mae: 2.0936
Epoch 8/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.6450 - mae: 1.9848 - val_loss: 7.0019 - val_mae: 2.0898
Epoch 9/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.5969 - mae: 1.9757 - val_loss: 7.0643 - val_mae: 2.1241
Epoch 10/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.5632 - mae: 1.9767 - val_loss: 7.0622 - val_mae: 2.1240
Epoch 11/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.4812 - mae: 1.9640 - val_loss: 7.0143 - val_mae: 2.1133
Epoch 12/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.4696 - mae: 1.9642 - val_loss: 7.0674 - val_mae: 2.1215
Epoch 13/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.4906 - mae: 1.9623 - val_loss: 6.6302 - val_mae: 2.0075
Epoch 14/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.4224 - mae: 1.9547 - val_loss: 7.1204 - val_mae: 2.1393
Epoch 15/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.4986 - mae: 1.9702 - val_loss: 7.4021 - val_mae: 2.2072
Epoch 16/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.4074 - mae: 1.9513 - val_loss: 6.8628 - val_mae: 2.0861
Epoch 17/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.3225 - mae: 1.9404 - val_loss: 7.3610 - val_mae: 2.1967
Epoch 18/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 6.2835 - mae: 1.9363 - val_loss: 7.2871 - val_mae: 2.1859
Epoch 19/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.2511 - mae: 1.9273 - val_loss: 6.5233 - val_mae: 1.9916
Epoch 20/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.3473 - mae: 1.9439 - val_loss: 6.7649 - val_mae: 2.0668
Epoch 21/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.3171 - mae: 1.9363 - val_loss: 7.6270 - val_mae: 2.2270
Epoch 22/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.4042 - mae: 1.9535 - val_loss: 6.9655 - val_mae: 2.1182
Epoch 23/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.2047 - mae: 1.9168 - val_loss: 6.9626 - val_mae: 2.1162
Epoch 24/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.1876 - mae: 1.9159 - val_loss: 8.6858 - val_mae: 2.3753
Epoch 25/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.3718 - mae: 1.9440 - val_loss: 7.3869 - val_mae: 2.2118
Epoch 26/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.2760 - mae: 1.9339 - val_loss: 6.9464 - val_mae: 2.1158
Epoch 27/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.1831 - mae: 1.9179 - val_loss: 6.9770 - val_mae: 2.1242
Epoch 28/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.1509 - mae: 1.9115 - val_loss: 6.5250 - val_mae: 2.0138
Epoch 29/100
97/97 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 6.1372 - mae: 1.9061 - val_loss: 7.0175 - val_mae: 2.1202

In [ ]:
pred = final_attention_model.predict(
    [
        X_cell_test,
        X_drug_test
    ]
)

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

from scipy.stats import pearsonr
import numpy as np

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        pred
    )
)

mae = mean_absolute_error(
    y_test,
    pred
)

r2 = r2_score(
    y_test,
    pred
)

pearson = pearsonr(
    y_test.flatten(),
    pred.flatten()
)[0]

print("RMSE:", rmse)
print("MAE:", mae)
print("R2:", r2)
print("Pearson:", pearson)

WARNING:tensorflow:5 out of the last 125 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7eecff4a9b20> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

121/121 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step
RMSE: 2.5407612365242183
MAE: 1.998426715393183
R2: 0.16960276916799433
Pearson: 0.4426948846698851

In [ ]:
import pandas as pd

results = pd.DataFrame({
    "Model":[
        "No Attention",
        "Attention",
        "Attention + Mutation",
        "Task-Aware + Mutation + Attention",
        "XGBoost"
    ],
    "Pearson":[
        0.353,
        0.672,
        0.423,
        0.412,
        0.914
    ],
    "R2":[
        0.089,
        0.376,
        0.136,
        0.151,
        0.835
    ]
})

results.to_csv(
    "model_comparison_results.csv",
    index=False
)

In [ ]:
#End to End GNN:

In [ ]:
import pandas as pd

smiles_df = pd.read_csv("GDSC_FULL_SMILES.csv")

print(smiles_df.shape)
print(smiles_df.columns)
smiles_df.head()

(229, 2)
Index(['Drug', 'CanonicalSMILES'], dtype='object')

           Drug                                    CanonicalSMILES
0  Camptothecin  CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=CC=CC=C5N=C4C3...
1   Vinblastine  CCC1(CC2CC(C3=C(CCN(C2)C1)C4=CC=CC=C4N3)(C5=C(...
2     Cisplatin                                       N.N.Cl[Pt]Cl
3    Cytarabine                 C1=CN(C(=O)N=C1N)C2C(C(C(O2)CO)O)O
4     Docetaxel  CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)...

In [ ]:
from rdkit import Chem

mol = Chem.MolFromSmiles(
    smiles_df.iloc[0]["CanonicalSMILES"]
)

print(mol)
print("Atoms:", mol.GetNumAtoms())
print("Bonds:", mol.GetNumBonds())

<rdkit.Chem.rdchem.Mol object at 0x7eecfa9e3d80>
Atoms: 26
Bonds: 30

In [ ]:
from rdkit import Chem
import torch
from torch_geometric.data import Data

def mol_to_graph(smiles):

    mol = Chem.MolFromSmiles(smiles)

    if mol is None:
        return None

    x = []

    for atom in mol.GetAtoms():

        x.append([
            atom.GetAtomicNum(),
            atom.GetDegree(),
            atom.GetFormalCharge(),
            int(atom.GetIsAromatic()),
            atom.GetTotalNumHs()
        ])

    edge_index = []

    for bond in mol.GetBonds():

        start = bond.GetBeginAtomIdx()
        end = bond.GetEndAtomIdx()

        edge_index.append([start, end])
        edge_index.append([end, start])

    x = torch.tensor(
        x,
        dtype=torch.float
    )

    edge_index = torch.tensor(
        edge_index,
        dtype=torch.long
    ).t().contiguous()

    return Data(
        x=x,
        edge_index=edge_index
    )

In [ ]:
drug_graphs = {}

for _, row in smiles_df.iterrows():

    drug = row["Drug"]
    smiles = row["CanonicalSMILES"]

    graph = mol_to_graph(smiles)

    if graph is not None:

        drug_graphs[drug] = graph

print("Graphs Created:", len(drug_graphs))

Graphs Created: 229

In [ ]:
sample_drug = list(drug_graphs.keys())[0]

print(sample_drug)

print(drug_graphs[sample_drug])

Camptothecin
Data(x=[26, 5], edge_index=[2, 60])

In [ ]:
print(training_task.shape)

print(training_task[[
    "DRUG_NAME",
    "LN_IC50"
]].head())

(19207, 546)
      DRUG_NAME   LN_IC50
0  Camptothecin  0.528845
1  Camptothecin -1.629546
2  Camptothecin -1.762080
3  Camptothecin -1.157607
4  Camptothecin -1.839524

In [ ]:
drug_to_idx = {
    drug:i
    for i, drug in enumerate(
        drug_graphs.keys()
    )
}

print(len(drug_to_idx))

229

In [ ]:
cell_cols = [f"cell_{i}" for i in range(256)]

mutation_cols = [
    "TP53","EGFR","KRAS","STK11",
    "KEAP1","BRAF","PIK3CA","ALK",
    "ROS1","MET","ERBB2","NF1",
    "RB1","SMARCA4","CDKN2A","PTEN"
]

X_cell = training_task[
    cell_cols + mutation_cols
].values

y = training_task[
    "LN_IC50"
].values

drug_names = training_task[
    "DRUG_NAME"
].values

print(X_cell.shape)
print(y.shape)
print(len(drug_names))

(19207, 272)
(19207,)
19207

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np

indices = np.arange(
    len(training_task)
)

train_idx, test_idx = train_test_split(
    indices,
    test_size=0.2,
    random_state=42
)

print(len(train_idx))
print(len(test_idx))

15365
3842

In [ ]:
import torch
from torch.utils.data import Dataset

class DrugResponseDataset(Dataset):

    def __init__(
        self,
        indices,
        X_cell,
        drug_names,
        y,
        drug_graphs
    ):

        self.indices = indices
        self.X_cell = X_cell
        self.drug_names = drug_names
        self.y = y
        self.drug_graphs = drug_graphs

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, idx):

        i = self.indices[idx]

        cell = torch.tensor(
            self.X_cell[i],
            dtype=torch.float
        )

        graph = self.drug_graphs[
            self.drug_names[i]
        ]

        target = torch.tensor(
            self.y[i],
            dtype=torch.float
        )

        return (
            cell,
            graph,
            target
        )

In [ ]:
print(X_cell.shape)

print(len(train_idx))
print(len(test_idx))

(19207, 272)
15365
3842

In [ ]:
import pandas as pd

embeddings = pd.read_csv(
    "TASK_AWARE_CANCER_EMBEDDINGS.csv"
)

mutations = pd.read_csv(
    "MUTATION_MATRIX.csv"
)

task_aware_cell_features = embeddings.merge(
    mutations,
    on="ModelID",
    how="inner"
)

print(task_aware_cell_features.shape)

task_aware_cell_features.to_csv(
    "TASK_AWARE_CELL_FEATURES.csv",
    index=False
)

print("TASK_AWARE_CELL_FEATURES.csv saved")

(92, 273)
TASK_AWARE_CELL_FEATURES.csv saved

In [ ]:
import torch
from torch_geometric.data import Data

training_task["graph"] = training_task["DRUG_NAME"].map(
    drug_graphs
)

print(
    training_task["graph"].isnull().sum()
)

print(
    training_task["graph"].iloc[0]
)

0
Data(x=[26, 5], edge_index=[2, 60])

In [ ]:
from torch.utils.data import Dataset

cell_cols = [f"cell_{i}" for i in range(256)]

mutation_cols = [
    "TP53","EGFR","KRAS","STK11",
    "KEAP1","BRAF","PIK3CA","ALK",
    "ROS1","MET","ERBB2","NF1",
    "RB1","SMARCA4","CDKN2A","PTEN"
]

class DrugResponseDataset(Dataset):

    def __init__(self, df):

        self.df = df.reset_index(drop=True)

    def __len__(self):

        return len(self.df)

    def __getitem__(self, idx):

        row = self.df.iloc[idx]

        cell = torch.tensor(
            row[cell_cols + mutation_cols].values,
            dtype=torch.float
        )

        graph = row["graph"]

        target = torch.tensor(
            row["LN_IC50"],
            dtype=torch.float
        )

        return cell, graph, target

In [ ]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    training_task,
    test_size=0.2,
    random_state=42
)

print(train_df.shape)
print(test_df.shape)

(15365, 547)
(3842, 547)

In [ ]:
from torch_geometric.data import Batch

def collate_fn(batch):

    cells = []
    graphs = []
    targets = []

    for cell, graph, target in batch:

        cells.append(cell)
        graphs.append(graph)
        targets.append(target)

    cells = torch.stack(cells)

    targets = torch.stack(targets)

    graph_batch = Batch.from_data_list(
        graphs
    )

    return (
        cells,
        graph_batch,
        targets
    )

In [ ]:
feature_cols = cell_cols + mutation_cols

print(
    training_task[feature_cols].dtypes.value_counts()
)

float32    256
int64       16
Name: count, dtype: int64

In [ ]:
bad_cols = training_task[
    feature_cols
].select_dtypes(
    include=["object"]
).columns

print(bad_cols)
print("Count:", len(bad_cols))

Index([], dtype='object')
Count: 0

In [ ]:
def __getitem__(self, idx):

    cell = torch.tensor(
        self.df.iloc[idx][
            cell_cols + mutation_cols
        ].to_numpy(dtype="float32"),
        dtype=torch.float32
    )

    graph = self.df.iloc[idx]["graph"]

    target = torch.tensor(
        self.df.iloc[idx]["LN_IC50"],
        dtype=torch.float32
    )

    return cell, graph, target

In [ ]:
feature_array = train_df.iloc[
    0
][
    cell_cols + mutation_cols
].to_numpy(dtype=np.float32)

print(feature_array.shape)
print(feature_array.dtype)

(272,)
float32

In [ ]:
class DrugResponseDataset(Dataset):

    def __init__(self, df):
        self.df = df.reset_index(drop=True)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):

        cell = torch.tensor(
            self.df.iloc[idx][
                cell_cols + mutation_cols
            ].to_numpy(dtype=np.float32),
            dtype=torch.float32
        )

        graph = self.df.iloc[idx]["graph"]

        target = torch.tensor(
            float(
                self.df.iloc[idx]["LN_IC50"]
            ),
            dtype=torch.float32
        )

        return cell, graph, target

In [ ]:
train_dataset = DrugResponseDataset(train_df)
test_dataset = DrugResponseDataset(test_df)

In [ ]:
sample = train_dataset[0]

print(sample[0].shape)
print(sample[1])
print(sample[2])

torch.Size([272])
Data(x=[26, 5], edge_index=[2, 60])
tensor(0.3925)

In [ ]:
train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True,
    collate_fn=collate_fn
)

test_loader = DataLoader(
    test_dataset,
    batch_size=64,
    shuffle=False,
    collate_fn=collate_fn
)

In [ ]:
cells, graphs, targets = next(
    iter(train_loader)
)

print(cells.shape)
print(graphs)
print(targets.shape)

torch.Size([64, 272])
DataBatch(x=[2028, 5], edge_index=[2, 4424], batch=[2028], ptr=[65])
torch.Size([64])

In [ ]:
import torch
import torch.nn as nn

from torch_geometric.nn import (
    GCNConv,
    global_mean_pool
)

class DrugGNN(nn.Module):

    def __init__(self):

        super().__init__()

        self.conv1 = GCNConv(
            5,
            64
        )

        self.conv2 = GCNConv(
            64,
            128
        )

        self.fc = nn.Linear(
            128,
            256
        )

    def forward(
        self,
        x,
        edge_index,
        batch
    ):

        x = self.conv1(
            x,
            edge_index
        )

        x = torch.relu(x)

        x = self.conv2(
            x,
            edge_index
        )

        x = torch.relu(x)

        x = global_mean_pool(
            x,
            batch
        )

        x = self.fc(x)

        return x


class DrugResponseGNN(nn.Module):

    def __init__(self):

        super().__init__()

        self.drug_gnn = DrugGNN()

        self.cell_fc = nn.Linear(
            272,
            256
        )

        self.fc1 = nn.Linear(
            512,
            512
        )

        self.fc2 = nn.Linear(
            512,
            256
        )

        self.fc3 = nn.Linear(
            256,
            128
        )

        self.out = nn.Linear(
            128,
            1
        )

        self.dropout = nn.Dropout(
            0.3
        )

    def forward(
        self,
        cell_features,
        graph_batch
    ):

        drug_embedding = self.drug_gnn(
            graph_batch.x.float(),
            graph_batch.edge_index,
            graph_batch.batch
        )

        cell_embedding = torch.relu(
            self.cell_fc(
                cell_features
            )
        )

        x = torch.cat(
            [
                cell_embedding,
                drug_embedding
            ],
            dim=1
        )

        x = torch.relu(
            self.fc1(x)
        )

        x = self.dropout(x)

        x = torch.relu(
            self.fc2(x)
        )

        x = self.dropout(x)

        x = torch.relu(
            self.fc3(x)
        )

        x = self.out(x)

        return x.squeeze()

In [ ]:
device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "cpu"
)

model = DrugResponseGNN().to(
    device
)

criterion = nn.MSELoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=1e-4
)

print(device)

cuda

In [ ]:
cells, graphs, targets = next(
    iter(train_loader)
)

cells = cells.to(device)
graphs = graphs.to(device)

pred = model(
    cells,
    graphs
)

print(pred.shape)

torch.Size([64])

In [ ]:
from tqdm import tqdm

num_epochs = 30

train_losses = []

for epoch in range(num_epochs):

    model.train()

    epoch_loss = 0

    loop = tqdm(
        train_loader,
        leave=False
    )

    for cells, graphs, targets in loop:

        cells = cells.to(device)

        graphs = graphs.to(device)

        targets = targets.to(device)

        optimizer.zero_grad()

        preds = model(
            cells,
            graphs
        )

        loss = criterion(
            preds,
            targets
        )

        loss.backward()

        optimizer.step()

        epoch_loss += loss.item()

    avg_loss = (
        epoch_loss /
        len(train_loader)
    )

    train_losses.append(
        avg_loss
    )

    print(
        f"Epoch {epoch+1}/{num_epochs} "
        f"Loss: {avg_loss:.4f}"
    )

Epoch 1/30 Loss: 8.2957

Epoch 2/30 Loss: 7.1157

Epoch 3/30 Loss: 6.9381

Epoch 4/30 Loss: 6.7875

Epoch 5/30 Loss: 6.6484

Epoch 6/30 Loss: 6.4789

Epoch 7/30 Loss: 6.3071

Epoch 8/30 Loss: 6.1609

Epoch 9/30 Loss: 5.9888

Epoch 10/30 Loss: 5.7409

Epoch 11/30 Loss: 5.6540

Epoch 12/30 Loss: 5.6367

Epoch 13/30 Loss: 5.5546

Epoch 14/30 Loss: 5.4266

Epoch 15/30 Loss: 5.4033

Epoch 16/30 Loss: 5.3887

Epoch 17/30 Loss: 5.2469

Epoch 18/30 Loss: 5.2591

Epoch 19/30 Loss: 5.2080

Epoch 20/30 Loss: 5.0636

Epoch 21/30 Loss: 4.9899

Epoch 22/30 Loss: 4.9123

Epoch 23/30 Loss: 4.8603

Epoch 24/30 Loss: 4.7035

Epoch 25/30 Loss: 4.6789

Epoch 26/30 Loss: 4.6189

Epoch 27/30 Loss: 4.5788

Epoch 28/30 Loss: 4.4817

Epoch 29/30 Loss: 4.4319

Epoch 30/30 Loss: 4.4508

In [ ]:
import numpy as np
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)
from scipy.stats import pearsonr

model.eval()

all_preds = []
all_targets = []

with torch.no_grad():

    for cells, graphs, targets in test_loader:

        cells = cells.to(device)

        graphs = graphs.to(device)

        preds = model(
            cells,
            graphs
        )

        all_preds.extend(
            preds.cpu().numpy()
        )

        all_targets.extend(
            targets.numpy()
        )

rmse = np.sqrt(
    mean_squared_error(
        all_targets,
        all_preds
    )
)

mae = mean_absolute_error(
    all_targets,
    all_preds
)

r2 = r2_score(
    all_targets,
    all_preds
)

pearson = pearsonr(
    all_targets,
    all_preds
)[0]

print("RMSE:", rmse)
print("MAE:", mae)
print("R2:", r2)
print("Pearson:", pearson)

RMSE: 2.1306428568109275
MAE: 1.669834102445778
R2: 0.41604484243741713
Pearson: 0.65099716

In [ ]:
torch.save(
    model.state_dict(),
    "END_TO_END_DRUG_GNN.pth"
)

print("Model Saved")

Model Saved

In [ ]:
import pandas as pd

gnn_results = pd.DataFrame({
    "Model": ["End-to-End Drug GNN"],
    "RMSE": [rmse],
    "MAE": [mae],
    "R2": [r2],
    "Pearson": [pearson]
})

gnn_results.to_csv(
    "end_to_end_gnn_results.csv",
    index=False
)

print("Results Saved")

Results Saved

In [ ]:
from tqdm import tqdm

num_epochs = 100

train_losses = []

for epoch in range(num_epochs):

    model.train()

    epoch_loss = 0

    loop = tqdm(
        train_loader,
        leave=False
    )

    for cells, graphs, targets in loop:

        cells = cells.to(device)

        graphs = graphs.to(device)

        targets = targets.to(device)

        optimizer.zero_grad()

        preds = model(
            cells,
            graphs
        )

        loss = criterion(
            preds,
            targets
        )

        loss.backward()

        optimizer.step()

        epoch_loss += loss.item()

    avg_loss = (
        epoch_loss /
        len(train_loader)
    )

    train_losses.append(
        avg_loss
    )

    print(
        f"Epoch {epoch+1}/{num_epochs} "
        f"Loss: {avg_loss:.4f}"
    )

Epoch 1/100 Loss: 4.3005

Epoch 2/100 Loss: 4.3276

Epoch 3/100 Loss: 4.3406

Epoch 4/100 Loss: 4.2819

Epoch 5/100 Loss: 4.2739

Epoch 6/100 Loss: 4.2450

Epoch 7/100 Loss: 4.2527

Epoch 8/100 Loss: 4.1514

Epoch 9/100 Loss: 4.0873

Epoch 10/100 Loss: 4.0580

Epoch 11/100 Loss: 4.0663

Epoch 12/100 Loss: 4.0709

Epoch 13/100 Loss: 4.0156

Epoch 14/100 Loss: 3.9532

Epoch 15/100 Loss: 3.9839

Epoch 16/100 Loss: 3.8766

Epoch 17/100 Loss: 3.9406

Epoch 18/100 Loss: 3.8666

Epoch 19/100 Loss: 3.8875

Epoch 20/100 Loss: 3.8553

Epoch 21/100 Loss: 3.8505

Epoch 22/100 Loss: 3.7493

Epoch 23/100 Loss: 3.6900

Epoch 24/100 Loss: 3.6901

Epoch 25/100 Loss: 3.6820

Epoch 26/100 Loss: 3.6631

Epoch 27/100 Loss: 3.6205

Epoch 28/100 Loss: 3.5865

Epoch 29/100 Loss: 3.6132

Epoch 30/100 Loss: 3.5101

Epoch 31/100 Loss: 3.5726

Epoch 32/100 Loss: 3.4988

Epoch 33/100 Loss: 3.4898

Epoch 34/100 Loss: 3.4242

Epoch 35/100 Loss: 3.4178

Epoch 36/100 Loss: 3.4230

Epoch 37/100 Loss: 3.4693

Epoch 38/100 Loss: 3.3648

Epoch 39/100 Loss: 3.3381

Epoch 40/100 Loss: 3.2951

Epoch 41/100 Loss: 3.2710

Epoch 42/100 Loss: 3.2857

Epoch 43/100 Loss: 3.2344

Epoch 44/100 Loss: 3.2198

Epoch 45/100 Loss: 3.2014

Epoch 46/100 Loss: 3.1830

Epoch 47/100 Loss: 3.2114

Epoch 48/100 Loss: 3.2335

Epoch 49/100 Loss: 3.1455

Epoch 50/100 Loss: 3.0638

Epoch 51/100 Loss: 3.0914

Epoch 52/100 Loss: 3.0592

Epoch 53/100 Loss: 3.0348

Epoch 54/100 Loss: 3.0843

Epoch 55/100 Loss: 2.9543

Epoch 56/100 Loss: 3.0248

Epoch 57/100 Loss: 2.9852

Epoch 58/100 Loss: 2.9502

Epoch 59/100 Loss: 2.9035

Epoch 60/100 Loss: 2.9226

Epoch 61/100 Loss: 2.8821

Epoch 62/100 Loss: 2.9569

Epoch 63/100 Loss: 2.8535

Epoch 64/100 Loss: 2.7950

Epoch 65/100 Loss: 2.7638

Epoch 66/100 Loss: 2.7876

Epoch 67/100 Loss: 2.7912

Epoch 68/100 Loss: 2.7221

Epoch 69/100 Loss: 2.7306

Epoch 70/100 Loss: 2.6534

Epoch 71/100 Loss: 2.6294

Epoch 72/100 Loss: 2.5941

Epoch 73/100 Loss: 2.6372

Epoch 74/100 Loss: 2.5951

Epoch 75/100 Loss: 2.5596

Epoch 76/100 Loss: 2.5258

Epoch 77/100 Loss: 2.5102

Epoch 78/100 Loss: 2.4697

Epoch 79/100 Loss: 2.4597

Epoch 80/100 Loss: 2.4275

Epoch 81/100 Loss: 2.4183

Epoch 82/100 Loss: 2.4082

Epoch 83/100 Loss: 2.3875

Epoch 84/100 Loss: 2.2982

Epoch 85/100 Loss: 2.3018

Epoch 86/100 Loss: 2.2811

Epoch 87/100 Loss: 2.2717

Epoch 88/100 Loss: 2.2514

Epoch 89/100 Loss: 2.2584

Epoch 90/100 Loss: 2.1875

Epoch 91/100 Loss: 2.1821

Epoch 92/100 Loss: 2.1588

Epoch 93/100 Loss: 2.1351

Epoch 94/100 Loss: 2.1572

Epoch 95/100 Loss: 2.1010

Epoch 96/100 Loss: 2.0989

Epoch 97/100 Loss: 2.0867

Epoch 98/100 Loss: 2.0554

Epoch 99/100 Loss: 2.0535

Epoch 100/100 Loss: 2.0156

In [ ]:
import numpy as np
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)
from scipy.stats import pearsonr

model.eval()

all_preds = []
all_targets = []

with torch.no_grad():

    for cells, graphs, targets in test_loader:

        cells = cells.to(device)
        graphs = graphs.to(device)

        preds = model(
            cells,
            graphs
        )

        all_preds.extend(
            preds.cpu().numpy()
        )

        all_targets.extend(
            targets.numpy()
        )

rmse = np.sqrt(
    mean_squared_error(
        all_targets,
        all_preds
    )
)

mae = mean_absolute_error(
    all_targets,
    all_preds
)

r2 = r2_score(
    all_targets,
    all_preds
)

pearson = pearsonr(
    all_targets,
    all_preds
)[0]

print("RMSE:", rmse)
print("MAE:", mae)
print("R2:", r2)
print("Pearson:", pearson)

RMSE: 1.4876110690769604
MAE: 1.1579456719141288
R2: 0.7153330919790654
Pearson: 0.8469973

In [ ]:
torch.save(
    model.state_dict(),
    "END_TO_END_DRUG_GNN_130_EPOCHS.pth"
)

print("Saved")

Saved

In [ ]:
import pandas as pd

results = pd.DataFrame({
    "Model": [
        "No Attention",
        "Attention",
        "Attention + Mutation",
        "Task-Aware + Mutation + Attention",
        "End-to-End Drug GNN (30 Epochs)",
        "End-to-End Drug GNN (130 Epochs)",
        "XGBoost"
    ],
    "RMSE": [
        2.6615,
        2.20,
        2.5910,
        2.5692,
        2.1306,
        1.4876,
        1.1339
    ],
    "R2": [
        0.0888,
        0.3760,
        0.1364,
        0.1509,
        0.4160,
        0.7153,
        0.8346
    ],
    "Pearson": [
        0.3525,
        0.6720,
        0.4228,
        0.4121,
        0.6510,
        0.8470,
        0.9138
    ]
})

results.to_csv(
    "FINAL_MODEL_COMPARISON.csv",
    index=False
)

print("FINAL_MODEL_COMPARISON.csv saved")
print(results)

FINAL_MODEL_COMPARISON.csv saved
                               Model    RMSE      R2  Pearson
0                       No Attention  2.6615  0.0888   0.3525
1                          Attention  2.2000  0.3760   0.6720
2               Attention + Mutation  2.5910  0.1364   0.4228
3  Task-Aware + Mutation + Attention  2.5692  0.1509   0.4121
4    End-to-End Drug GNN (30 Epochs)  2.1306  0.4160   0.6510
5   End-to-End Drug GNN (130 Epochs)  1.4876  0.7153   0.8470
6                            XGBoost  1.1339  0.8346   0.9138

In [ ]:
gnn_best = pd.DataFrame({
    "Model": ["End-to-End Drug GNN (130 Epochs)"],
    "RMSE": [1.4876110690769604],
    "MAE": [1.1579456719141288],
    "R2": [0.7153330919790654],
    "Pearson": [0.8469973]
})

gnn_best.to_csv(
    "BEST_GNN_RESULTS.csv",
    index=False
)

print("BEST_GNN_RESULTS.csv saved")

BEST_GNN_RESULTS.csv saved

In [ ]:
from tqdm import tqdm

num_epochs = 60

for epoch in range(num_epochs):

    model.train()

    epoch_loss = 0

    for cells, graphs, targets in tqdm(
        train_loader,
        leave=False
    ):

        cells = cells.to(device)
        graphs = graphs.to(device)
        targets = targets.to(device)

        optimizer.zero_grad()

        preds = model(
            cells,
            graphs
        )

        loss = criterion(
            preds,
            targets
        )

        loss.backward()

        optimizer.step()

        epoch_loss += loss.item()

    avg_loss = epoch_loss / len(train_loader)

    print(
        f"Extra Epoch {epoch+1}/60 "
        f"Loss: {avg_loss:.4f}"
    )

Extra Epoch 1/60 Loss: 2.7597

Extra Epoch 2/60 Loss: 2.4034

Extra Epoch 3/60 Loss: 2.2769

Extra Epoch 4/60 Loss: 2.2435

Extra Epoch 5/60 Loss: 2.2578

Extra Epoch 6/60 Loss: 2.2173

Extra Epoch 7/60 Loss: 2.1140

Extra Epoch 8/60 Loss: 2.0957

Extra Epoch 9/60 Loss: 2.1061

Extra Epoch 10/60 Loss: 2.1527

Extra Epoch 11/60 Loss: 2.0580

Extra Epoch 12/60 Loss: 1.9778

Extra Epoch 13/60 Loss: 1.9862

Extra Epoch 14/60 Loss: 1.9643

Extra Epoch 15/60 Loss: 1.9521

Extra Epoch 16/60 Loss: 1.9541

Extra Epoch 17/60 Loss: 1.9160

Extra Epoch 18/60 Loss: 1.8922

Extra Epoch 19/60 Loss: 1.8812

Extra Epoch 20/60 Loss: 1.9331

Extra Epoch 21/60 Loss: 1.8753

Extra Epoch 22/60 Loss: 1.8452

Extra Epoch 23/60 Loss: 1.8084

Extra Epoch 24/60 Loss: 1.7969

Extra Epoch 25/60 Loss: 1.7700

Extra Epoch 26/60 Loss: 1.7845

Extra Epoch 27/60 Loss: 1.7924

Extra Epoch 28/60 Loss: 1.7498

Extra Epoch 29/60 Loss: 1.7303

Extra Epoch 30/60 Loss: 1.7278

Extra Epoch 31/60 Loss: 1.7018

Extra Epoch 32/60 Loss: 1.6864

Extra Epoch 33/60 Loss: 1.7060

Extra Epoch 34/60 Loss: 1.6537

Extra Epoch 35/60 Loss: 1.6450

Extra Epoch 36/60 Loss: 1.6619

Extra Epoch 37/60 Loss: 1.6465

Extra Epoch 38/60 Loss: 1.6068

Extra Epoch 39/60 Loss: 1.6210

Extra Epoch 40/60 Loss: 1.5847

Extra Epoch 41/60 Loss: 1.5790

Extra Epoch 42/60 Loss: 1.5742

Extra Epoch 43/60 Loss: 1.6045

Extra Epoch 44/60 Loss: 1.5386

Extra Epoch 45/60 Loss: 1.5431

Extra Epoch 46/60 Loss: 1.5292

Extra Epoch 47/60 Loss: 1.5197

Extra Epoch 48/60 Loss: 1.4768

Extra Epoch 49/60 Loss: 1.4737

Extra Epoch 50/60 Loss: 1.4961

Extra Epoch 51/60 Loss: 1.4941

Extra Epoch 52/60 Loss: 1.4452

Extra Epoch 53/60 Loss: 1.4515

Extra Epoch 54/60 Loss: 1.4079

Extra Epoch 55/60 Loss: 1.3747

Extra Epoch 56/60 Loss: 1.4252

Extra Epoch 57/60 Loss: 1.4234

Extra Epoch 58/60 Loss: 1.4002

Extra Epoch 59/60 Loss: 1.3655

Extra Epoch 60/60 Loss: 1.3864

In [ ]:
#190 Epoch:

import numpy as np
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)
from scipy.stats import pearsonr

model.eval()

all_preds = []
all_targets = []

with torch.no_grad():

    for cells, graphs, targets in test_loader:

        cells = cells.to(device)
        graphs = graphs.to(device)

        preds = model(
            cells,
            graphs
        )

        all_preds.extend(
            preds.cpu().numpy()
        )

        all_targets.extend(
            targets.numpy()
        )

rmse = np.sqrt(
    mean_squared_error(
        all_targets,
        all_preds
    )
)

mae = mean_absolute_error(
    all_targets,
    all_preds
)

r2 = r2_score(
    all_targets,
    all_preds
)

pearson = pearsonr(
    all_targets,
    all_preds
)[0]

print("RMSE:", rmse)
print("MAE:", mae)
print("R2:", r2)
print("Pearson:", pearson)

RMSE: 1.296848159263507
MAE: 1.0019929292493
R2: 0.7836601911590502
Pearson: 0.8856659

In [ ]:
import torch

torch.save(
    model.state_dict(),
    "BEST_END_TO_END_DRUG_GNN_190_EPOCHS.pth"
)

print("Best model saved successfully!")

Best model saved successfully!

In [ ]:
import pandas as pd

best_result = pd.DataFrame({
    "Model": ["End-to-End Drug GNN (190 Epochs)"],
    "RMSE": [1.296848159263507],
    "MAE": [1.0019929292493],
    "R2": [0.7836601911590502],
    "Pearson": [0.8856659]
})

best_result.to_csv(
    "BEST_GNN_RESULTS.csv",
    index=False
)

print("BEST_GNN_RESULTS.csv saved")

BEST_GNN_RESULTS.csv saved

In [ ]:
import pandas as pd

final_results = pd.DataFrame({
    "Model": [
        "No Attention",
        "Attention",
        "Attention + Mutation",
        "Task-Aware + Mutation + Attention",
        "End-to-End Drug GNN (30 Epochs)",
        "End-to-End Drug GNN (130 Epochs)",
        "End-to-End Drug GNN (170 Epochs)",
        "End-to-End Drug GNN (190 Epochs)",
        "XGBoost"
    ],

    "RMSE": [
        2.6615,
        2.2000,
        2.5910,
        2.5692,
        2.1306,
        1.4876,
        1.3551,
        1.2968,
        1.1339
    ],

    "MAE": [
        2.1159,
        None,
        2.0655,
        2.0281,
        1.6698,
        1.1579,
        1.0514,
        1.0020,
        0.8645
    ],

    "R2": [
        0.0888,
        0.3760,
        0.1364,
        0.1509,
        0.4160,
        0.7153,
        0.7638,
        0.7837,
        0.8346
    ],

    "Pearson": [
        0.3525,
        0.6720,
        0.4228,
        0.4121,
        0.6510,
        0.8470,
        0.8761,
        0.8857,
        0.9138
    ]
})

final_results.to_csv(
    "FINAL_MODEL_COMPARISON.csv",
    index=False
)

print("FINAL_MODEL_COMPARISON.csv saved")

FINAL_MODEL_COMPARISON.csv saved

In [ ]:
#210 epoches

from tqdm import tqdm

num_epochs = 20

for epoch in range(num_epochs):

    model.train()

    epoch_loss = 0

    for cells, graphs, targets in tqdm(
        train_loader,
        leave=False
    ):

        cells = cells.to(device)
        graphs = graphs.to(device)
        targets = targets.to(device)

        optimizer.zero_grad()

        preds = model(
            cells,
            graphs
        )

        loss = criterion(
            preds,
            targets
        )

        loss.backward()

        optimizer.step()

        epoch_loss += loss.item()

    avg_loss = (
        epoch_loss /
        len(train_loader)
    )

    print(
        f"Extra Epoch {epoch+1}/20 "
        f"Loss: {avg_loss:.4f}"
    )

Extra Epoch 1/20 Loss: 1.3873

Extra Epoch 2/20 Loss: 1.3483

Extra Epoch 3/20 Loss: 1.3422

Extra Epoch 4/20 Loss: 1.3345

Extra Epoch 5/20 Loss: 1.3263

Extra Epoch 6/20 Loss: 1.3551

Extra Epoch 7/20 Loss: 1.3175

Extra Epoch 8/20 Loss: 1.3088

Extra Epoch 9/20 Loss: 1.2964

Extra Epoch 10/20 Loss: 1.2611

Extra Epoch 11/20 Loss: 1.2521

Extra Epoch 12/20 Loss: 1.2320

Extra Epoch 13/20 Loss: 1.2581

Extra Epoch 14/20 Loss: 1.2790

Extra Epoch 15/20 Loss: 1.2412

Extra Epoch 16/20 Loss: 1.2352

Extra Epoch 17/20 Loss: 1.2205

Extra Epoch 18/20 Loss: 1.2009

Extra Epoch 19/20 Loss: 1.1927

Extra Epoch 20/20 Loss: 1.2197

In [1]:
#230 epoch:

from tqdm import tqdm

num_epochs = 20

for epoch in range(num_epochs):

    model.train()

    epoch_loss = 0

    for cells, graphs, targets in tqdm(
        train_loader,
        leave=False
    ):

        cells = cells.to(device)
        graphs = graphs.to(device)
        targets = targets.to(device)

        optimizer.zero_grad()

        preds = model(
            cells,
            graphs
        )

        loss = criterion(
            preds,
            targets
        )

        loss.backward()

        optimizer.step()

        epoch_loss += loss.item()

    avg_loss = (
        epoch_loss /
        len(train_loader)
    )

    print(
        f"Extra Epoch {epoch+1}/20 "
        f"Loss: {avg_loss:.4f}"
    )

Extra Epoch 1/20 Loss: 1.2247
Extra Epoch 2/20 Loss: 1.1637
Extra Epoch 3/20 Loss: 1.1373
Extra Epoch 4/20 Loss: 1.0988
Extra Epoch 5/20 Loss: 1.0829
Extra Epoch 6/20 Loss: 1.0441
Extra Epoch 7/20 Loss: 1.0163
Extra Epoch 8/20 Loss: 0.9476
Extra Epoch 9/20 Loss: 0.9246
Extra Epoch 10/20 Loss: 0.8725
Extra Epoch 11/20 Loss: 0.8436
Extra Epoch 12/20 Loss: 0.8187
Extra Epoch 13/20 Loss: 0.7631
Extra Epoch 14/20 Loss: 0.7336
Extra Epoch 15/20 Loss: 0.7152
Extra Epoch 16/20 Loss: 0.6746
Extra Epoch 17/20 Loss: 0.6252
Extra Epoch 18/20 Loss: 0.6035
Extra Epoch 19/20 Loss: 0.5759
Extra Epoch 20/20 Loss: 0.5271

In [2]:
#230 epoches ouptut:

import numpy as np
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)
from scipy.stats import pearsonr

model.eval()

all_preds = []
all_targets = []

with torch.no_grad():

    for cells, graphs, targets in test_loader:

        cells = cells.to(device)
        graphs = graphs.to(device)

        preds = model(
            cells,
            graphs
        )

        all_preds.extend(
            preds.cpu().numpy()
        )

        all_targets.extend(
            targets.numpy()
        )

rmse = np.sqrt(
    mean_squared_error(
        all_targets,
        all_preds
    )
)

mae = mean_absolute_error(
    all_targets,
    all_preds
)

r2 = r2_score(
    all_targets,
    all_preds
)

pearson = pearsonr(
    all_targets,
    all_preds
)[0]

print("RMSE:", rmse)
print("MAE:", mae)
print("R2:", r2)
print("Pearson:", pearson)

RMSE: 1.053482761945813
MAE: 0.814297563182941
R2: 0.858436712594821
Pearson: 0.92718453

In [ ]:
torch.save(
    model.state_dict(),
    "BEST_END_TO_END_DRUG_GNN_230_EPOCHS.pth"
)

print("Final model saved")

Final model saved

In [4]:
import pandas as pd

final_results = pd.DataFrame({

    "Model": [
        "Linear Regression",
        "XGBoost",
        "No Attention",
        "Attention",
        "Attention + Mutation",
        "Task-Aware + Mutation + Attention",
        "End-to-End Drug GNN (30 Epochs)",
        "End-to-End Drug GNN (130 Epochs)",
        "End-to-End Drug GNN (170 Epochs)",
        "End-to-End Drug GNN (190 Epochs)",
        "End-to-End Drug GNN (230 Epochs)"
    ],

    "RMSE": [
        1.1935,
        1.1339,
        2.6615,
        2.2000,
        2.5910,
        2.5692,
        2.1306,
        1.4876,
        1.3551,
        1.2968,
        1.053482761945813
    ],

    "MAE": [
        0.9097,
        0.8645,
        2.1159,
        None,
        2.0655,
        2.0281,
        1.6698,
        1.1579,
        1.0514,
        1.0020,
        0.814297563182941
    ],

    "R2": [
        0.8168,
        0.8346,
        0.0888,
        0.3760,
        0.1364,
        0.1509,
        0.4160,
        0.7153,
        0.7638,
        0.7837,
        0.858436712594821
    ],

    "Pearson": [
        0.9039,
        0.9138,
        0.3525,
        0.6720,
        0.4228,
        0.4121,
        0.6510,
        0.8470,
        0.8761,
        0.8857,
        0.92718453
    ]

})

final_results.to_csv(
    "FINAL_PROJECT_RESULTS.csv",
    index=False
)

print(final_results)
print("\nFINAL_PROJECT_RESULTS.csv saved successfully")

                                Model      RMSE       MAE        R2   Pearson
0                   Linear Regression  1.193500  0.909700  0.816800  0.903900
1                             XGBoost  1.133900  0.864500  0.834600  0.913800
2                        No Attention  2.661500  2.115900  0.088800  0.352500
3                           Attention  2.200000       NaN  0.376000  0.672000
4                Attention + Mutation  2.591000  2.065500  0.136400  0.422800
5   Task-Aware + Mutation + Attention  2.569200  2.028100  0.150900  0.412100
6     End-to-End Drug GNN (30 Epochs)  2.130600  1.669800  0.416000  0.651000
7    End-to-End Drug GNN (130 Epochs)  1.487600  1.157900  0.715300  0.847000
8    End-to-End Drug GNN (170 Epochs)  1.355100  1.051400  0.763800  0.876100
9    End-to-End Drug GNN (190 Epochs)  1.296800  1.002000  0.783700  0.885700
10   End-to-End Drug GNN (230 Epochs)  1.053483  0.814298  0.858437  0.927185

FINAL_PROJECT_RESULTS.csv saved successfully